export const DEFAULT_PROFILE_BACKGROUND_SLUG = 'solid-slate';
export const LEGACY_PROFILE_BACKGROUND_SLUGS = ['gradient-midnight', 'solid-ink', 'solid-dark'];
export const DEFAULT_PROFILE_BACKGROUND_IMAGE_URL = 'solid:#2d4057';

export const PROFILE_BACKGROUND_SEEDS = [
  { slug: 'gradient-blue', name: 'Blue', image_url: 'gradient:linear-gradient(135deg,#0d1117,#0a2a4a)' },
  { slug: 'gradient-purple', name: 'Purple', image_url: 'gradient:linear-gradient(135deg,#0d1117,#1a0a2e)' },
  { slug: 'gradient-green', name: 'Green', image_url: 'gradient:linear-gradient(135deg,#0d1117,#0a2e1a)' },
  { slug: 'gradient-red', name: 'Red', image_url: 'gradient:linear-gradient(135deg,#0d1117,#2e0a0a)' },
  { slug: 'gradient-orange', name: 'Orange', image_url: 'gradient:linear-gradient(135deg,#0d1117,#2e1a0a)' },
  { slug: 'gradient-pink', name: 'Pink', image_url: 'gradient:linear-gradient(135deg,#1a0d1a,#2e0a1e)' },
  { slug: 'gradient-teal', name: 'Teal', image_url: 'gradient:linear-gradient(135deg,#0d1a1a,#0a2e2a)' },
  { slug: 'gradient-gold', name: 'Gold', image_url: 'gradient:linear-gradient(135deg,#1a1400,#2e2800)' },
  { slug: 'gradient-sunset', name: 'Sunset', image_url: 'gradient:linear-gradient(135deg,#1a0800,#2e1500,#1a0a2e)' },
  { slug: 'gradient-ocean', name: 'Ocean', image_url: 'gradient:linear-gradient(135deg,#000d1a,#001a33,#0a2a4a)' },
  { slug: 'gradient-forest', name: 'Forest', image_url: 'gradient:linear-gradient(135deg,#001a0d,#0a2e1a,#001a0d)' },
  { slug: 'gradient-midnight', name: 'Legacy Midnight', image_url: 'gradient:linear-gradient(135deg,#050510,#0d0d2e,#05050e)', is_default: 0 },
  { slug: 'gradient-rose', name: 'Rose', image_url: 'gradient:linear-gradient(135deg,#1a0010,#2e0020,#1a000d)' },
  { slug: 'gradient-cyber', name: 'Cyber', image_url: 'gradient:linear-gradient(135deg,#000d1a,#001a1a,#0a2e2a)' },
  { slug: 'gradient-lava', name: 'Lava', image_url: 'gradient:linear-gradient(135deg,#1a0000,#2e0a00,#1a1400)' },
  { slug: 'solid-ink', name: 'Legacy Dark', image_url: 'solid:#0b0f14', is_default: 0 },
  { slug: 'solid-dark', name: 'Legacy Dark 2', image_url: 'solid:#10151c', is_default: 0 },
  { slug: 'solid-charcoal', name: 'Charcoal', image_url: 'solid:#161b22' },
  { slug: 'solid-black', name: 'Black', image_url: 'solid:#050505' },
  { slug: 'solid-navy', name: 'Navy', image_url: 'solid:#0a1020' },
  { slug: DEFAULT_PROFILE_BACKGROUND_SLUG, name: 'Default Slate', image_url: DEFAULT_PROFILE_BACKGROUND_IMAGE_URL },
  { slug: 'solid-brown', name: 'Brown', image_url: 'solid:#2b2118' },
  { slug: 'solid-olive', name: 'Olive', image_url: 'solid:#1f2a1d' },
  { slug: 'solid-wine', name: 'Wine', image_url: 'solid:#2b1118' },
  { slug: 'solid-cream', name: 'Cream', image_url: 'solid:#f3ead7' },
  { slug: 'photo-1', name: 'Background 1', image_url: '/backgrounds/background.avif' },
  { slug: 'photo-2', name: 'Background 2', image_url: '/backgrounds/background2.avif' },
  { slug: 'photo-3', name: 'Background 3', image_url: '/backgrounds/background3.avif' },
  { slug: 'photo-4', name: 'Background 4', image_url: '/backgrounds/background4.jpg' },
  { slug: 'focus-grid', name: 'Focus Grid', image_url: 'gradient:linear-gradient(135deg,#0b1220 0%,#10263d 48%,#162018 100%)', is_default: 0 },
  { slug: 'night-judge', name: 'Night Judge', image_url: 'gradient:linear-gradient(135deg,#080b10 0%,#172033 42%,#1f1a12 100%)', is_default: 0 },
];
