export const REWARD_SEEDS = [
  { code: 'badge_bronze', type: 'badge', name: '브론즈 달성', description: '브론즈 티어 달성', rarity: 'common', icon: '🥉' },
  { code: 'badge_silver', type: 'badge', name: '실버 달성', description: '실버 티어 달성', rarity: 'common', icon: '🥈' },
  { code: 'badge_gold', type: 'badge', name: '골드 달성', description: '골드 티어 달성', rarity: 'uncommon', icon: '🥇' },
  { code: 'badge_platinum', type: 'badge', name: '플래티넘 달성', description: '플래티넘 티어 달성', rarity: 'rare', icon: '💎' },
  { code: 'badge_diamond', type: 'badge', name: '다이아 달성', description: '다이아 티어 달성', rarity: 'epic', icon: '💠' },
  { code: 'badge_xp_rookie', type: 'badge', name: '루키', description: 'XP 레벨 2 달성', rarity: 'common', icon: '🌱' },
  { code: 'badge_xp_climber', type: 'badge', name: '클라이머', description: 'XP 레벨 5 달성', rarity: 'uncommon', icon: '⛰️' },
  { code: 'badge_xp_veteran', type: 'badge', name: '베테랑', description: 'XP 레벨 10 달성', rarity: 'rare', icon: '🏆' },
  { code: 'badge_first_solve', type: 'badge', name: '첫 풀이', description: '첫 문제 해결', rarity: 'common', icon: '🎯' },
  { code: 'badge_streak_7', type: 'badge', name: '7일 연속', description: '7일 연속 풀이', rarity: 'uncommon', icon: '🔥' },
  { code: 'badge_streak_30', type: 'badge', name: '한 달 연속', description: '30일 연속 풀이', rarity: 'rare', icon: '⚡' },
  { code: 'badge_battle_win', type: 'badge', name: '첫 배틀 승리', description: '배틀 첫 승리', rarity: 'uncommon', icon: '⚔️' },
  { code: 'title_bronze', type: 'title', name: '브론즈 코더', description: '브론즈 달성', rarity: 'common', icon: null },
  { code: 'title_silver', type: 'title', name: '실버 코더', description: '실버 달성', rarity: 'common', icon: null },
  { code: 'title_gold', type: 'title', name: '골드 코더', description: '골드 달성', rarity: 'uncommon', icon: null },
  { code: 'title_platinum', type: 'title', name: '플래티넘 코더', description: '플래티넘 달성', rarity: 'rare', icon: null },
  { code: 'title_diamond', type: 'title', name: '다이아 코더', description: '다이아 달성', rarity: 'epic', icon: null },
  { code: 'title_routine_builder', type: 'title', name: '꾸준한 코더', description: 'XP 레벨 3 달성', rarity: 'common', icon: null },
  { code: 'title_debug_maker', type: 'title', name: '디버그 마스터', description: 'XP 레벨 7 달성', rarity: 'uncommon', icon: null },
];
