export const REWARD_SEEDS = [
  // ── Ranking (tier achieved) ───────────────────────────────────────────────
  { code: 'badge_bronze',      type: 'badge', name: 'Bronze Achieved',     nameKo: '브론즈 달성',      description: 'Reached Bronze tier.',                    descriptionKo: '브론즈 티어에 도달했습니다.',          rarity: 'common',    icon: '🥉', category: 'ranking', sort_order: 10 },
  { code: 'badge_silver',      type: 'badge', name: 'Silver Achieved',     nameKo: '실버 달성',        description: 'Reached Silver tier.',                    descriptionKo: '실버 티어에 도달했습니다.',            rarity: 'common',    icon: '🥈', category: 'ranking', sort_order: 20 },
  { code: 'badge_gold',        type: 'badge', name: 'Gold Achieved',       nameKo: '골드 달성',        description: 'Reached Gold tier.',                      descriptionKo: '골드 티어에 도달했습니다.',            rarity: 'uncommon',  icon: '🥇', category: 'ranking', sort_order: 30 },
  { code: 'badge_platinum',    type: 'badge', name: 'Platinum Achieved',   nameKo: '플래티넘 달성',    description: 'Reached Platinum tier.',                  descriptionKo: '플래티넘 티어에 도달했습니다.',        rarity: 'rare',      icon: '💎', category: 'ranking', sort_order: 40 },
  { code: 'badge_emerald',     type: 'badge', name: 'Emerald Achieved',    nameKo: '에메랄드 달성',    description: 'Reached Emerald tier.',                   descriptionKo: '에메랄드 티어에 도달했습니다.',        rarity: 'rare',      icon: '💚', category: 'ranking', sort_order: 50 },
  { code: 'badge_diamond',     type: 'badge', name: 'Diamond Achieved',    nameKo: '다이아몬드 달성',  description: 'Reached Diamond tier.',                   descriptionKo: '다이아몬드 티어에 도달했습니다.',      rarity: 'epic',      icon: '💠', category: 'ranking', sort_order: 60 },
  { code: 'badge_master',      type: 'badge', name: 'Master Achieved',     nameKo: '마스터 달성',      description: 'Reached Master tier.',                    descriptionKo: '마스터 티어에 도달했습니다.',          rarity: 'epic',      icon: '🔮', category: 'ranking', sort_order: 70 },
  { code: 'badge_grandmaster', type: 'badge', name: 'Grandmaster',         nameKo: '그랜드마스터',     description: 'Reached Grandmaster tier.',               descriptionKo: '그랜드마스터 티어에 도달했습니다.',    rarity: 'legendary', icon: '🌙', category: 'ranking', sort_order: 80 },
  { code: 'badge_challenger',  type: 'badge', name: 'Challenger',          nameKo: '챌린저',           description: 'Your name is in the server TOP 3.',       descriptionKo: '서버 TOP 3에 이름을 올렸습니다.',      rarity: 'legendary', icon: '⚡', category: 'ranking', sort_order: 90 },

  // ── Coding (problems solved) ──────────────────────────────────────────────
  { code: 'badge_first_solve', type: 'badge', name: 'First Solve',         nameKo: '첫 번째 풀이',     description: 'Solved your first problem.',              descriptionKo: '첫 번째 문제를 풀었습니다.',           rarity: 'common',    icon: '🎯', category: 'coding', sort_order: 10 },
  { code: 'badge_solve10',     type: 'badge', name: '10 Problems Solved',  nameKo: '문제 10개 해결',   description: 'Solved 10 problems.',                     descriptionKo: '문제 10개를 해결했습니다.',            rarity: 'common',    icon: '✅', category: 'coding', sort_order: 20 },
  { code: 'badge_solve50',     type: 'badge', name: '50 Problems Solved',  nameKo: '문제 50개 해결',   description: 'Solved 50 problems.',                     descriptionKo: '문제 50개를 해결했습니다.',            rarity: 'uncommon',  icon: '🎖️', category: 'coding', sort_order: 30 },
  { code: 'badge_solve100',    type: 'badge', name: '100 Problems Solved', nameKo: '문제 100개 해결',  description: 'Solved 100 problems.',                    descriptionKo: '문제 100개를 해결했습니다.',           rarity: 'rare',      icon: '🏅', category: 'coding', sort_order: 40 },
  { code: 'badge_solve200',    type: 'badge', name: '200 Problems Solved', nameKo: '문제 200개 해결',  description: 'Solved 200 problems.',                    descriptionKo: '문제 200개를 해결했습니다.',           rarity: 'epic',      icon: '🎗️', category: 'coding', sort_order: 50 },
  { code: 'badge_solve500',    type: 'badge', name: 'Algorithm Master',    nameKo: '알고리즘 마스터',  description: 'Legendary coder who solved 500 problems.', descriptionKo: '문제 500개를 해결한 전설의 코더.',     rarity: 'legendary', icon: '👑', category: 'coding', sort_order: 60 },

  // ── Streak (consecutive solves) ───────────────────────────────────────────
  { code: 'badge_streak_7',    type: 'badge', name: '7-Day Streak',        nameKo: '7일 연속',         description: 'Solved problems 7 days in a row.',        descriptionKo: '7일 연속으로 문제를 풀었습니다.',      rarity: 'uncommon',  icon: '🔥', category: 'streak', sort_order: 10 },
  { code: 'badge_streak_30',   type: 'badge', name: '30-Day Streak',       nameKo: '30일 연속',        description: 'Solved problems 30 days in a row.',       descriptionKo: '30일 연속으로 문제를 풀었습니다.',     rarity: 'rare',      icon: '⚡', category: 'streak', sort_order: 20 },
  { code: 'badge_streak100',   type: 'badge', name: '100-Day Streak',      nameKo: '100일 연속',       description: 'Solved problems 100 days in a row.',      descriptionKo: '100일 연속으로 문제를 풀었습니다.',    rarity: 'epic',      icon: '💥', category: 'streak', sort_order: 30 },
  { code: 'badge_streak365',   type: 'badge', name: '365-Day Streak',      nameKo: '365일 연속',       description: 'Legendary streak of 365 days.',           descriptionKo: '전설적인 365일 연속 기록.',            rarity: 'legendary', icon: '🌟', category: 'streak', sort_order: 40 },

  // ── XP (level) ───────────────────────────────────────────────────────────
  { code: 'badge_xp_rookie',   type: 'badge', name: 'Rookie',              nameKo: '루키',             description: 'Reached XP level 2.',                    descriptionKo: 'XP 레벨 2에 도달했습니다.',           rarity: 'common',    icon: '🌱', category: 'xp', sort_order: 10 },
  { code: 'badge_xp_climber',  type: 'badge', name: 'Climber',             nameKo: '클라이머',         description: 'Reached XP level 5.',                    descriptionKo: 'XP 레벨 5에 도달했습니다.',           rarity: 'uncommon',  icon: '⛰️', category: 'xp', sort_order: 20 },
  { code: 'badge_xp_veteran',  type: 'badge', name: 'Veteran',             nameKo: '베테랑',           description: 'Reached XP level 10.',                   descriptionKo: 'XP 레벨 10에 도달했습니다.',          rarity: 'rare',      icon: '🏆', category: 'xp', sort_order: 30 },
  { code: 'badge_xp_master',   type: 'badge', name: 'XP Master',           nameKo: 'XP 마스터',        description: 'Reached XP level 20.',                   descriptionKo: 'XP 레벨 20에 도달했습니다.',          rarity: 'epic',      icon: '🌠', category: 'xp', sort_order: 40 },

  // ── Battle ────────────────────────────────────────────────────────────────
  { code: 'badge_battle_win',    type: 'badge', name: 'First Battle Win',  nameKo: '첫 배틀 승리',     description: 'Won your first battle.',                  descriptionKo: '첫 번째 배틀에서 승리했습니다.',       rarity: 'uncommon',  icon: '⚔️', category: 'battle', sort_order: 10 },
  { code: 'badge_battle_5wins',  type: 'badge', name: '5 Battle Wins',     nameKo: '5승',              description: 'Won 5 battles.',                          descriptionKo: '배틀에서 5승을 달성했습니다.',         rarity: 'rare',      icon: '🗡️', category: 'battle', sort_order: 20 },
  { code: 'badge_battle_10wins', type: 'badge', name: '10 Battle Wins',    nameKo: '10승',             description: 'Won 10 battles.',                         descriptionKo: '배틀에서 10승을 달성했습니다.',        rarity: 'epic',      icon: '🛡️', category: 'battle', sort_order: 30 },
  { code: 'badge_battle_20wins', type: 'badge', name: 'Battle Dominator',  nameKo: '배틀 지배자',      description: 'Dominator with 20 battle wins.',          descriptionKo: '배틀 20승을 달성한 지배자.',           rarity: 'legendary', icon: '👊', category: 'battle', sort_order: 40 },

  // ── Explore (challenge badges) ────────────────────────────────────────────
  { code: 'badge_speedrun',    type: 'badge', name: 'Speedrun',            nameKo: '스피드런',         description: 'Solved a problem within 10 minutes.',     descriptionKo: '10분 이내에 문제를 풀었습니다.',       rarity: 'uncommon',  icon: '⏱️', category: 'explore', sort_order: 10 },
  { code: 'badge_nightowl',    type: 'badge', name: 'Night Owl',           nameKo: '야행성',           description: 'Solved a problem between midnight and 4am.', descriptionKo: '자정~새벽 4시 사이에 문제를 풀었습니다.', rarity: 'uncommon', icon: '🦉', category: 'explore', sort_order: 20 },
  { code: 'badge_gold_killer', type: 'badge', name: 'Gold Killer',         nameKo: '골드 킬러',        description: 'First solved a Gold or higher problem.',  descriptionKo: '골드 이상 문제를 처음으로 풀었습니다.', rarity: 'rare',     icon: '✨', category: 'explore', sort_order: 30 },
  { code: 'badge_multilang',   type: 'badge', name: 'Polyglot',            nameKo: '멀티 언어',        description: 'Answered correctly in 3 or more languages.', descriptionKo: '3개 이상의 언어로 정답을 제출했습니다.', rarity: 'rare',  icon: '🌐', category: 'explore', sort_order: 40 },

  // ── Titles ────────────────────────────────────────────────────────────────
  { code: 'title_bronze',          type: 'title', name: 'Bronze Coder',     nameKo: '브론즈 코더',     description: 'Bronze Achieved',       descriptionKo: '브론즈 달성',     rarity: 'common',   icon: null, category: 'ranking', sort_order: 10 },
  { code: 'title_silver',          type: 'title', name: 'Silver Coder',     nameKo: '실버 코더',       description: 'Silver Achieved',       descriptionKo: '실버 달성',       rarity: 'common',   icon: null, category: 'ranking', sort_order: 20 },
  { code: 'title_gold',            type: 'title', name: 'Gold Coder',       nameKo: '골드 코더',       description: 'Gold Achieved',         descriptionKo: '골드 달성',       rarity: 'uncommon', icon: null, category: 'ranking', sort_order: 30 },
  { code: 'title_platinum',        type: 'title', name: 'Platinum Coder',   nameKo: '플래티넘 코더',   description: 'Platinum Achieved',     descriptionKo: '플래티넘 달성',   rarity: 'rare',     icon: null, category: 'ranking', sort_order: 40 },
  { code: 'title_diamond',         type: 'title', name: 'Diamond Coder',    nameKo: '다이아몬드 코더', description: 'Diamond Achieved',      descriptionKo: '다이아몬드 달성', rarity: 'epic',     icon: null, category: 'ranking', sort_order: 50 },
  { code: 'title_routine_builder',  type: 'title', name: 'Consistent Coder',  nameKo: '꾸준한 코더',      description: 'XP level 3 achieved',                  descriptionKo: 'XP 레벨 3 달성',           rarity: 'common',    icon: null, category: 'xp',      sort_order: 10 },
  { code: 'title_debug_maker',      type: 'title', name: 'Debug Master',      nameKo: '디버그 마스터',    description: 'XP level 7 achieved',                  descriptionKo: 'XP 레벨 7 달성',           rarity: 'uncommon',  icon: null, category: 'xp',      sort_order: 20 },
  { code: 'title_emerald',          type: 'title', name: 'Emerald Coder',     nameKo: '에메랄드 코더',    description: 'Emerald tier achieved',                 descriptionKo: '에메랄드 달성',             rarity: 'rare',      icon: null, category: 'ranking', sort_order: 55 },
  { code: 'title_master',           type: 'title', name: 'Master Coder',      nameKo: '마스터 코더',      description: 'Master tier achieved',                  descriptionKo: '마스터 달성',               rarity: 'epic',      icon: null, category: 'ranking', sort_order: 65 },
  { code: 'title_first_solve',      type: 'title', name: 'First Stepper',     nameKo: '첫 발자국',        description: 'First problem solved',                  descriptionKo: '첫 번째 문제를 풀었습니다.', rarity: 'common',    icon: null, category: 'coding',  sort_order: 5  },
  { code: 'title_solve100',         type: 'title', name: 'Problem Veteran',   nameKo: '백전노장',          description: '100 problems solved',                   descriptionKo: '문제 100개 해결',           rarity: 'rare',      icon: null, category: 'coding',  sort_order: 15 },
  { code: 'title_streak_7',         type: 'title', name: 'Streak Keeper',     nameKo: '꾸준한 풀이어',    description: '7-day solving streak',                  descriptionKo: '7일 연속 풀이',             rarity: 'uncommon',  icon: null, category: 'streak',  sort_order: 5  },
  { code: 'title_night_coder',      type: 'title', name: 'Night Coder',       nameKo: '밤샘 코더',        description: 'Solved between midnight and 4am',       descriptionKo: '자정~새벽 4시 사이에 풀이', rarity: 'uncommon',  icon: null, category: 'explore', sort_order: 5  },
  { code: 'title_speedster',        type: 'title', name: 'Speedster',         nameKo: '스피드런 마스터',   description: 'Solved a problem within 10 minutes',    descriptionKo: '10분 이내 문제 해결',       rarity: 'uncommon',  icon: null, category: 'explore', sort_order: 10 },
  { code: 'title_multilang_coder',  type: 'title', name: 'Polyglot Coder',    nameKo: '멀티 언어 코더',   description: 'Correct answers in 3+ languages',       descriptionKo: '3개 이상 언어로 정답 제출',  rarity: 'rare',      icon: null, category: 'explore', sort_order: 20 },
];
