ALTER TABLE tournaments ADD COLUMN is_private TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE tournaments ADD COLUMN join_password VARCHAR(100) DEFAULT NULL;
ALTER TABLE tournaments ADD COLUMN min_tier VARCHAR(20) DEFAULT NULL;
ALTER TABLE tournaments ADD COLUMN max_tier VARCHAR(20) DEFAULT NULL;
ALTER TABLE tournaments ADD COLUMN banned_tags TEXT DEFAULT NULL;
