ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS is_private TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS join_password VARCHAR(100) DEFAULT NULL;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS min_tier VARCHAR(20) DEFAULT NULL;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS max_tier VARCHAR(20) DEFAULT NULL;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS banned_tags TEXT DEFAULT NULL;
