import { createContext, useContext, useMemo, useState } from 'react';

const LangContext = createContext(null);

const STRINGS = {
  ko: {
    // ── Navigation ─────────────────────────────
    problems: '문제',
    contest: '대회',
    ranking: '랭킹',
    community: '커뮤니티',
    battle: '배틀',
    settings: '설정',
    logout: '로그아웃',
    profile: '프로필',
    myProfile: '내 프로필',
    mypage: '마이페이지',
    exams: '모의 코테',
    sheets: '문제 세트',
    learning: '단계별 학습',
    subscribe: '구독 관리',
    pricing: '요금제',
    ai: 'AI 분석',
    submissions: '제출 내역',
    admin: '관리',
    team: '팀',
    // ── Theme / Language ────────────────────────
    darkMode: '다크 모드',
    lightMode: '라이트 모드',
    systemMode: '시스템 설정',
    language: '언어',
    // ── Notifications ───────────────────────────
    notifications: '알림',
    markAllRead: '모두 읽음',
    noNotifications: '알림이 없습니다',
    // ── Common UI ───────────────────────────────
    save: '저장',
    saving: '저장 중…',
    cancel: '취소',
    close: '닫기',
    confirm: '확인',
    delete: '삭제',
    edit: '편집',
    back: '뒤로',
    next: '다음',
    prev: '이전',
    search: '검색',
    filter: '필터',
    sort: '정렬',
    loading: '로딩 중…',
    loadingMore: '더 불러오는 중…',
    noData: '데이터가 없습니다',
    noResults: '검색 결과가 없어요',
    tryAgain: '다시 시도',
    showMore: '더 보기',
    showLess: '접기',
    copied: '복사됨',
    copyFailed: '링크 복사에 실패했습니다',
    share: '공유',
    submit: '제출',
    run: '실행',
    upgrade: '업그레이드',
    // ── Stats ───────────────────────────────────
    tier: '티어',
    solved: '해결',
    rating: '레이팅',
    streak: '연속 풀이',
    today: '오늘',
    week: '이번 주',
    solvedCount: '문제',
    submissionCount: '제출',
    // ── Profile ─────────────────────────────────
    editProfile: '프로필 수정',
    saveProfile: '프로필 저장',
    bio: '소개',
    nickname: '닉네임',
    displayName: '표시 이름',
    socialLinks: '소셜 링크',
    techStack: '기술 스택',
    followers: '팔로워',
    following: '팔로잉',
    follow: '팔로우',
    unfollow: '언팔로우',
    changePassword: '비밀번호 변경',
    currentPassword: '현재 비밀번호',
    newPassword: '새 비밀번호',
    confirmPassword: '새 비밀번호 확인',
    // ── Auth ────────────────────────────────────
    login: '로그인',
    register: '회원가입',
    email: '이메일',
    password: '비밀번호',
    forgotPassword: '비밀번호 찾기',
    createAccount: '계정 만들기',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    noAccount: '계정이 없으신가요?',
    loginWithGoogle: 'Google로 계속하기',
    loginWithGithub: 'GitHub으로 계속하기',
    // ── Problems ────────────────────────────────
    problemList: '문제 목록',
    difficulty: '난이도',
    tags: '태그',
    unsolved: '미해결',
    bookmarked: '북마크',
    addBookmark: '북마크에 추가했습니다',
    removeBookmark: '북마크 해제',
    premium: '프리미엄',
    premiumOnly: '프리미엄 전용',
    randomProblem: '랜덤 미해결 뽑기',
    findingRandom: '랜덤 찾는 중',
    noSolvedProblems: '아직 푼 문제가 없어요',
    sortByMostSolved: '많이 푼 순',
    sortByLatest: '최신순',
    // ── Judge ────────────────────────────────────
    runCode: '코드 실행',
    submitCode: '제출',
    testCases: '테스트 케이스',
    output: '출력',
    accepted: '맞았습니다!',
    wrongAnswer: '틀렸습니다',
    timeLimitExceeded: '시간 초과',
    memoryLimitExceeded: '메모리 초과',
    runtimeError: '런타임 에러',
    compileError: '컴파일 에러',
    hint: '힌트',
    aiHint: 'AI 힌트',
    discuss: '토론',
    editorial: '해설',
    myCode: '내 코드',
    reset: '초기화',
    fontSize: '폰트 크기',
    // ── Community ────────────────────────────────
    post: '게시글',
    comment: '댓글',
    like: '좋아요',
    noComments: '댓글이 없습니다',
    writeComment: '댓글 작성',
    write: '작성하기',
    popularPosts: '인기글',
    recentPosts: '최신글',
    report: '신고',
    // ── Dashboard ────────────────────────────────
    welcome: '안녕하세요',
    recommendedProblems: '오늘의 추천 문제',
    tryProblem: '도전하기',
    quickAction: '빠른 액션',
    activityHeatmap: '활동 현황',
    growthChart: '성장 차트',
    weeklyChallenge: '이번 주 챌린지',
    // ── Battle ────────────────────────────────────
    findOpponent: '상대 찾기',
    battleHistory: '배틀 기록',
    spectate: '관전',
    win: '승리',
    lose: '패배',
    draw: '무승부',
    waiting: '대기 중',
    // ── Contest ───────────────────────────────────
    ongoing: '진행 중',
    upcoming: '예정',
    ended: '종료',
    joinContest: '참가 등록',
    // ── AI Page ───────────────────────────────────
    analyze: '분석',
    aiReview: 'AI 코드 리뷰',
    dailyQuiz: '오늘의 퀴즈',
    aiChat: 'AI 채팅',
    // ── Settings tabs ────────────────────────────
    profileTab: '프로필',
    notificationsTab: '알림',
    uiTab: '화면',
    editorTab: '에디터',
    privacyTab: '개인정보',
    accountTab: '계정',
    // ── Settings — UI ────────────────────────────
    animations: '애니메이션',
    animationsDesc: '페이지 전환 효과',
    compactMode: '콤팩트 모드',
    compactModeDesc: '문제 목록을 더 빽빽하게',
    autoCollapseSidebar: '사이드바 자동 접기',
    appFont: '앱 글씨체',
    appFontDesc: '저장하면 전체 화면 글씨체에 적용됩니다.',
    // ── Settings — editor ─────────────────────────
    autoSave: '자동 저장',
    autoSaveDesc: '30초마다 코드 자동 저장',
    minimap: '미니맵',
    minimapDesc: '에디터 우측 미니맵 표시',
    lineNumbers: '줄 번호',
    tabSize: '탭 크기',
    editorTheme: '에디터 테마',
    // ── Settings — notifications ──────────────────
    commentNotif: '댓글 알림',
    commentNotifDesc: '내 게시글에 댓글이 달릴 때',
    likeNotif: '좋아요 알림',
    likeNotifDesc: '게시글/댓글에 좋아요를 받을 때',
    followNotif: '팔로우 알림',
    followNotifDesc: '새 팔로워가 생길 때',
    mentionNotif: '@멘션 알림',
    mentionNotifDesc: '댓글에서 언급될 때',
    battleNotif: '배틀 알림',
    battleNotifDesc: '배틀 초대 및 결과',
    // ── Settings — privacy ────────────────────────
    profileVisibility: '프로필 공개 설정',
    postVisibility: '게시글 공개 설정',
    visPublic: '전체 공개',
    visFollowers: '팔로워만',
    visPrivate: '비공개',
    // ── Toast / status messages ───────────────────
    saveSuccess: '저장됐어요!',
    saveFailed: '저장 실패',
    loadFailed: '불러오지 못했습니다',
    profileSaved: '프로필이 저장됐어요!',
    passwordChanged: '비밀번호가 변경됐어요!',
    passwordMismatch: '비밀번호가 일치하지 않아요',
    passwordTooShort: '8자 이상으로 입력해주세요',
    settingsLoadFailed: '설정을 불러오지 못했습니다.',
    visibilitySaved: '공개 설정이 저장됐어요!',
    // ── ErrorBoundary ──────────────────────────────
    unexpectedError: '예상치 못한 오류가 발생했습니다',
    refreshFix: '페이지를 새로고침하면 해결될 수 있습니다.',
    errorDetails: '오류 세부 정보',
    refresh: '🔄 새로고침',
    goBack: '← 돌아가기',
    // ── EmailVerifyGate ────────────────────────────
    emailVerifyRequired: '이메일 인증이 필요합니다',
    afterVerification: '인증 후 이용 가능',
    resendEmailBtn: '📧 인증 이메일 재전송',
    sending: '전송 중...',
    emailResent: '✓ 인증 이메일을 재전송했습니다. 받은 편지함을 확인해주세요.',
    noVerifyForProblems: '문제 풀기는 인증 없이도 이용 가능합니다.',
    // ── NotFoundPage ───────────────────────────────
    pageNotFound: '페이지를 찾을 수 없습니다',
    pageNotFoundDesc: '요청하신 페이지가 존재하지 않거나 이동되었습니다.',
    pageNotFoundHint: 'URL을 확인하거나 아래 링크를 이용해주세요.',
    goHome: '🏠 홈으로',
    // ── Auth pages ─────────────────────────────────
    resetPassword: '비밀번호 재설정',
    resetPasswordDesc: '가입하신 이메일 주소를 입력하시면 재설정 링크를 보내드립니다.',
    sendResetLink: '재설정 링크 보내기',
    sendingLink: '발송 중...',
    checkEmail: '이메일을 확인해주세요',
    checkEmailDesc: '입력하신 이메일 주소로 비밀번호 재설정 링크를 발송했습니다. 받은 편지함 또는 스팸 폴더를 확인해주세요.',
    backToLogin: '로그인으로 돌아가기',
    setNewPassword: '새 비밀번호 설정',
    newPasswordDesc: '사용할 새 비밀번호를 입력해주세요.',
    invalidLink: '⚠️ 유효하지 않은 링크입니다. 비밀번호 재설정을 다시 요청해주세요.',
    passwordChangedTitle: '비밀번호가 변경됐습니다',
    passwordChangedRedirect: '새 비밀번호로 설정이 완료됐습니다. 3초 후 로그인 페이지로 이동합니다.',
    goToLogin: '로그인으로 이동',
    passwordMinLength: '비밀번호는 최소 8자 이상이어야 합니다.',
    passwordMismatch2: '비밀번호가 일치하지 않습니다.',
    resetFailed: '비밀번호 재설정에 실패했습니다. 링크가 만료되었을 수 있습니다.',
    changingPassword: '변경 중...',
    changePasswordBtn: '비밀번호 변경',
    min8Chars: '8자 이상 입력',
    reEnterPassword: '비밀번호 재입력',
    passwordsMatch: '✓ 비밀번호가 일치합니다',
    passwordsNoMatch: '✗ 비밀번호가 일치하지 않습니다',
    // ── VerifyEmailPage ────────────────────────────
    verifyingEmail: '이메일 인증 중...',
    pleaseWait: '잠시만 기다려주세요.',
    verifySuccess: '인증이 완료됐습니다!',
    verifySuccessDesc: '이메일 인증에 성공했습니다. 3초 후 대시보드로 자동 이동합니다.',
    goToDashboard: '대시보드로 이동',
    verifyFailed: '인증에 실패했습니다',
    invalidLinkSimple: '유효하지 않은 링크입니다.',
    verifyFailedDefault: '이메일 인증에 실패했습니다. 링크가 만료되었을 수 있습니다.',
    resendSuccess: '✓ 인증 이메일을 재전송했습니다. 받은 편지함을 확인해주세요.',
    resendRequest: '재전송 요청',
    // ── SharedSubmissionPage ───────────────────────
    loadingShare: '공유 링크를 불러오는 중...',
    sharedSubmission: '공유된 제출',
    cannotOpenLink: '공유 링크를 열 수 없습니다',
    goHomeLink: '홈으로 이동',
    codeLoading: '코드 로딩 중...',
    authorLabel: '작성자',
    resultLabel: '결과',
    langLabel: '언어',
    solveTimeLabel: '풀이 시간',
    codeLabel: '코드',
    // ── ProblemsPage ───────────────────────────────
    allTiers: '전체 티어',
    allTypes: '전체 유형',
    loadingTags: '태그 불러오는 중...',
    allTags: '전체 태그',
    sortById: '번호순',
    sortByEasy: '쉬운순',
    sortByHard: '어려운순',
    allStatus: '전체',
    solvedStatus: '해결',
    unsolvedStatus: '미해결',
    bookmarkStatus: '북마크',
    viewingAll: '전체 문제를 보고 있어요',
    copyFilterLink: '필터 링크 복사',
    clearAll: '초기화',
    solve: '풀기 →',
    solveProblem: '💻 풀기 시작 →',
    loadingProblems: '문제 목록을 불러오는 중입니다',
    noResultsHint: '다른 조건으로 검색하거나 랜덤 미해결 뽑기를 써보세요.',
    manageProblem: '문제 관리',
    upgradeAndSolve: '🔒 Pro 플랜으로 업그레이드하고 풀기',
    prevPage: '← 이전',
    nextPage: '다음 →',
    onboardingRec: '🎯 온보딩 추천 문제',
    sortByNewest: '최신순',
    sortBySolved: '많이 푼 순',
    randomPicking: '랜덤 찾는 중...',
    randomPick: '랜덤 미해결 뽑기',
    localFallback: '로컬 목록 폴백',
    filterLoadingDesc: '필터에 맞는 결과를 빠르게 준비하고 있어요.',
    hoverSolve: 'hover 시 바로 풀기 가능',
    problemNoDesc: '문제 설명은 상세 화면에서 확인할 수 있습니다.',
    searchPlaceholder: '문제 검색...',
    chipSearch: '검색: ',
    chipTier: '티어: ',
    chipType: '유형: ',
    chipTag: '태그: ',
    chipStatus: '상태: ',
    chipSort: '정렬: ',
    totalLabel: '전체',
    solvedLabel: '✓ 해결',
    unsolvedLabel: '◯ 미해결',
    currentResults: '현재 결과',
    pageInfo: '페이지 {page} / {total}',
    showingOf: '총 {total}개 중 {showing}개 표시',
    activeFilters: '활성 필터 {n}개',
    difficultyShort: '난이도',
    solversCount: '{n}명 정답',
    solversUnit: '{n}명',
    tableNumCol: '번호',
    tableTitleCol: '제목',
    tableTierCol: '티어',
    tableDiffCol: '난이도',
    tableSolversCol: '정답자',
    tableRateCol: '정답률',
    tableStatusCol: '상태',
    tableActionCol: '액션',
    exInput: '입력',
    exOutput: '출력',
    problemListTitle: '📋 문제 목록',
    filterLinkCopied: '현재 필터 링크를 복사했습니다.',
    filterLinkFailed: '링크 복사에 실패했습니다. 브라우저 권한을 확인해주세요.',
    bookmarkAdded: '🔖 북마크에 추가했습니다.',
    bookmarkRemoved: '북마크를 해제했습니다.',
    bookmarkFailed: '북마크 처리에 실패했습니다.',
    filterCleared: '필터를 초기화했습니다.',
    upgradeRequired: '프리미엄 전용 문제입니다. 업그레이드가 필요합니다.',
    randomNone: '조건에 맞는 문제가 없습니다.',
    randomFailed: '랜덤 문제를 불러오지 못했습니다.',
    randomPicked: '🎲 {title} 문제를 골랐어요.',
    loadFailed2: '문제 목록을 불러오지 못해 로컬 데이터로 표시합니다.',
    solvedBadge: '✅ 해결',
    premiumBadge: '🔒 프리미엄 전용',
    typeLabelCoding: '일반 풀이',
    typeShortCoding: '코딩',
    typeLabelFillBlank: '빈칸 채우기',
    typeShortFillBlank: '빈칸',
    typeLabelBugFix: '틀린부분 찾기',
    typeShortBugFix: '버그',
    secUnit: '초',
    // ── AiPage ────────────────────────────────────
    analyzingBtn: '✨ 내 실력 분석하기',
    analyzingStatus: '분석 중...',
    generatingQuiz: '생성 중...',
    aiOnline: '• 온라인',
    sendMessage: '전송',
    hintReceive: '힌트 받기',
    hintAnalyzing: '분석중',
    hintNoSelect: '-- 문제 선택 --',
    hintExceeded: '오늘 힌트를 모두 사용했습니다.',
    hintLimitTitle: '일일 힌트 한도 초과',
    noRecommendation: '추천할 문제가 없습니다. 더 많은 문제를 풀어보세요!',
    aiFeatureLabel: 'AI 기능',
    aiPageTitle: '🤖 AI 맞춤 추천',
    aiPageSubtitle: 'Gemini AI가 풀이 기록을 분석해 최적의 학습 경로를 제안합니다.',
    quotaUnlimited: '오늘 남은 횟수: 무제한 (Pro/Team)',
    quotaRemaining: '오늘 남은 횟수: {n}회',
    quotaExceeded: '오늘 AI 힌트를 모두 사용했습니다.',
    upgradeLink: 'Pro로 업그레이드',
    upgradeUnlimitedSuffix: '하면 무제한 사용 가능합니다.',
    todayQuizBtn: '🎯 오늘의 퀴즈',
    recommendCardTitle: '🎯 맞춤 추천 문제',
    recommendCardSubtitle: '내 티어 기반으로 아직 풀지 않은 문제를 추천해드립니다.',
    loadingText: '불러오는 중...',
    aiEmptyPrompt: '버튼을 눌러 AI 분석을 시작하세요.',
    aiEmptyPrompt2: 'Gemini AI가 맞춤 추천을 드립니다.',
    previewProblems: '문제 분석',
    previewStreak: '일 스트릭',
    previewTier: '티어',
    quizCardTitle: '🎯 오늘의 퀴즈',
    quizCorrect: '🎉 정답!',
    quizWrong: '❌ 오답!',
    quizRelatedConcept: '관련 개념: ',
    hintCardTitle: '💡 문제별 AI 힌트',
    hintCardSubtitle: '문제를 선택하면 단계별 힌트를 받을 수 있어요.',
    hintUpgradeLink: 'Pro로 업그레이드',
    hintUpgradeSuffix: '하면 무제한 이용 가능해요.',
    hintRemainingCount: '오늘 힌트 {n}회 남음 (무료 플랜)',
    hintProPlanLink: 'Pro 플랜 보기 →',
    hintLevelBtn: '힌트 {n}',
    hintCommonMistake: '⚠️ 흔한 실수: ',
    hintRelatedConcept: '관련 개념: ',
    aiAnalyzingText: 'Gemini AI가 분석하는 중...',
    analysisCurrentLevel: '📊 현재 실력',
    analysisStrengths: '💪 강점',
    analysisWeaknesses: '📈 보완 필요',
    analysisRecommended: '🎯 추천 문제',
    analysisStudyPlan: '📅 이번 주 학습 계획',
    defaultStudyPlan: '꾸준히 매일 1문제씩 풀어보세요!',
    chatWelcomeLine1: '안녕하세요, {username}님!',
    chatWelcomeLine2: '알고리즘 학습에 대해 무엇이든 물어보세요.',
    chatPlaceholder: '학습에 대해 질문하세요... (Enter로 전송)',
    chatRetryMsg: '잠시 후 다시 시도해주세요.',
    // ── BattlePage ─────────────────────────────────
    codingBattle: '코딩 배틀',
    inviteOpponent: '상대방 초대',
    sendInviteBtn: '초대 보내기',
    acceptBtn: '수락',
    declineBtn: '거절',
    activeBattlesTab: '진행 중인 배틀',
    historyTabLabel: '히스토리',
    activeBattlesSpectate: '진행 중인 배틀 (관전 가능)',
    noBattles: '현재 진행 중인 배틀이 없습니다.',
    spectateBtn: '관전하기',
    myBattleHistory: '내 배틀 히스토리',
    loadingHistory: '히스토리를 불러오는 중입니다.',
    noBattleHistory: '아직 완료된 배틀이 없습니다.',
    rematchBtn: '리매치',
    battleRules: '배틀 규칙',
    spectatorBanner: '👁️ 현재 배틀을 관전 중입니다 (읽기 전용)',
    freePlanBanner: '무료 플랜도 1:1 배틀을 이용할 수 있으며, 대신 광고 슬롯이 노출됩니다.',
    judgingCode: '채점 중...',
    wrongAnswerFeedback: '오답입니다. 다시 시도해보세요.',
    correctFeedback: '정답! 영토를 점령했습니다 🎉',
    battleWin: '🏆 승리!',
    battleDraw: '🤝 무승부',
    battleLose: '💀 패배',
    noRatingEffect: 'ℹ️ 배틀 결과는 레이팅/티어에 반영되지 않습니다.',
    battleAgain: '다시 배틀하기',
    battleSubtitle: '실시간으로 상대와 코딩 대결을 펼쳐보세요.',
    battleTagline: '모든 영토(문제)를 먼저 점령하는 팀이 승리!',
    inviteInputPlaceholder: '상대방 사용자명 입력',
    waitingAcceptance: '{name}님의 수락을 기다리는 중...',
    waitingSub: '상대방이 2분 내에 수락해야 합니다.',
    inviteReceived: '{name}님이 배틀을 신청했습니다!',
    inviteExpiry: '지금 수락하지 않으면 2분 후 자동 만료됩니다.',
    scoreHistory: '점수 {scoreFor} : {scoreAgainst} · 해결 {solvedFor} : {solvedAgainst}',
    rematchRequesting: '요청 중...',
    historyBtn: '🕘 히스토리',
    copyBtn: '📋 복사',
    twitterBtn: '🐦 트위터',
    opponentTypingLabel: '⌨️ 입력 중...',
    myTerritoryFlag: '🏳️ 내 것',
    lockedTerritoryFlag: '🔒 선점됨',
    lockedByOpponentBadge: '🔒 상대가 선점한 문제',
    myTeamFlag: '🏳️ 내 팀',
    oppTeamFlag: '🏴 상대 팀',
    teamCaptured: '{team}이 이 문제를 점령했습니다.',
    submitBtn: '제출',
    resultSelf: '(나)',
    resultPts: '{n}점',
    resultSolved: '{n}문제 풀이',
    territoryResult: '영토 결과',
    battleRuleTime: '⏱️ 제한 시간: <strong>30분</strong>',
    battleRuleTerritory: '🗺️ 영토 선점: 문제를 먼저 맞힌 팀이 영토를 점령하며, 상대 팀은 해당 문제를 풀 수 없습니다.',
    battleRuleTeam: '👥 팀 배틀: 팀원끼리 점수를 합산하며, 실시간으로 소통하며 문제를 나눠 풀어보세요.',
    battleRuleSpectate: '👁️ 관전 모드: 다른 플레이어의 배틀을 실시간으로 관전할 수 있습니다.',
    inviteFailedDefault: '초대 전송 실패',
    declinedInvite: '상대방이 초대를 거절했습니다.',
    spectateFailed: '관전에 실패했습니다.',
    shareShared: '결과를 공유했습니다.',
    shareCopied: '결과를 클립보드에 복사했습니다.',
    shareFailed: '결과 공유에 실패했습니다.',
    rematchSent: '리매치 요청을 보냈습니다.',
    rematchFailed: '리매치 요청에 실패했습니다.',
    hintPrefix: '💡 힌트: ',
    blankPlaceholder: '빈칸 {n}',
    bugfixLabel: '수정된 줄 입력:',
    bugfixPlaceholder: '버그가 있는 줄을 올바르게 수정해 입력하세요',
    exampleLabel: '예제 {n}',
    langUnspecified: '언어 미지정',
    resultCorrect: '✅ 정답',
    resultLocked: '🔒 선점됨',
    resultWrong: '❌ 오답',
    codePlaceholder: '코드를 입력하세요...',
    // ── ContestPage ────────────────────────────────
    contestMode: '🏆 대회 모드',
    contestAdminDesc: '대회를 만들고 관리하세요.',
    contestUserDesc: '대회에 참가해 실력을 겨뤄보세요.',
    createContestBtn: '+ 대회 만들기',
    allContests: '전체',
    liveContests: '진행중',
    endedContests: '종료',
    myContests: '내 대회',
    noContestsCurrent: '현재 대회가 없습니다.',
    createFirstContest: '아직 대회가 없습니다. 대회를 만들어보세요!',
    seeResults: '결과 보기',
    joinContestBtn: '참가 신청',
    enterNow: '🔴 지금 입장',
    joinDone: '✓ 참가 완료',
    approvalPending: '⏳ 승인 대기 중',
    // ── Additional i18n batch ─────────────────────
    sendFailedTryLater: '전송에 실패했습니다. 잠시 후 다시 시도해주세요.',
    verifyBannerMessage: '이메일 인증이 필요합니다. 받은 편지함을 확인해주세요.',
    mockAdRemoveTitle: '🚀 Pro 플랜으로 광고 제거',
    mockAdRemoveDesc: '더 쾌적한 환경에서 코딩에 집중하세요.',
    mockAdAiTitle: '💡 AI 힌트가 부족하신가요?',
    mockAdAiDesc: 'Pro 플랜은 무제한 AI 멘토링을 제공합니다.',
    mockAdRankingTitle: '🏆 랭킹 1위를 향하여',
    mockAdRankingDesc: '프리미엄 문제로 더 높은 레이팅을 획득하세요.',
    mockAdBenefitsCta: '혜택 확인하기',
    goalJobHunting: '코테 합격',
    goalJobHuntingDesc: '취업/이직 준비 중',
    goalSkillUp: '실력 향상',
    goalSkillUpDesc: '알고리즘 실력 키우기',
    goalInterviewPrep: '면접 준비',
    goalInterviewPrepDesc: '기술 면접 대비',
    goalFun: '그냥 재미',
    goalFunDesc: '꾸준히 즐기면서',
    onboardingBeginner: '초급',
    onboardingBeginnerDesc: '버블 정렬, 기본 문법 정도는 알아요',
    onboardingIntermediate: '중급',
    onboardingIntermediateDesc: '배열, 문자열, BFS/DFS는 어느 정도 풀 수 있어요',
    onboardingAdvanced: '고급',
    onboardingAdvancedDesc: '실전 코테를 꾸준히 준비 중이에요',
    onboardingGoalTitle: 'DailyCoding에 온 이유가 뭐예요?',
    onboardingGoalDesc: '당신에게 맞는 첫 문제와 학습 흐름을 준비하겠습니다.',
    onboardingLevelTitle: '현재 실력은 어느 정도인가요?',
    onboardingLevelDesc: '너무 어렵거나 너무 쉬운 문제를 피하도록 맞춥니다.',
    onboardingCompanyTitle: '어느 회사 코테를 준비하고 있나요?',
    onboardingCompanyDesc: '선택사항입니다. 입력하면 추천 문제를 조금 더 맞춰드립니다.',
    onboardingCompanyPlaceholder: '카카오, 네이버, 라인, 토스 ...',
    skip: '건너뛰기',
    getStarted: '시작하기',
    teamCreated: '팀이 생성되었습니다.',
    teamCreateFailed: '팀 생성 실패',
    teamInviteCopied: '초대 링크가 클립보드에 복사되었습니다. (7일간 유효)',
    teamInviteFailed: '링크 생성 실패',
    teamRemoveConfirm: '정말로 이 멤버를 팀에서 추방하시겠습니까?',
    teamMemberRemoved: '멤버가 추방되었습니다.',
    teamMemberRemoveFailed: '멤버 추방 실패',
    teamPlanOnlyTitle: 'Team 플랜 전용 페이지입니다.',
    teamPlanOnlyDesc: '팀 대시보드 기능을 이용하려면 플랜을 업그레이드하세요.',
    viewPricing: '요금제 보기',
    teamCreateTitle: '팀을 생성하세요',
    teamCreateDesc: '팀 플랜 멤버십이 활성화되었습니다. 팀 이름을 정하고 첫 팀을 만들어보세요.',
    teamNamePlaceholder: '팀 이름 입력 (예: 개발팀, 알고리즘 스터디)',
    teamCreateBtn: '팀 생성하기',
    teamManageDesc: '팀 멤버를 관리하고 학습 현황을 확인하세요.',
    teamInviteBtn: '멤버 초대하기',
    teamStatsBeta: '팀 통계 (Beta)',
    teamActiveMembers: '활성 멤버',
    teamWeeklySolved: '이번 주 해결 문제',
    teamWeeklySolvedCount: '{n}개',
    teamAvgRating: '평균 레이팅',
    teamRatingPoints: '{n}점',
    teamMemberList: '멤버 목록',
    teamUserCol: '사용자',
    teamRoleCol: '역할',
    teamJoinedAtCol: '가입일',
    teamStatusCol: '상태',
    teamActionCol: '액션',
    teamYou: '나',
    teamActiveStatus: '● 활성',
    teamRemoveBtn: '추방',
    examListDesc: '실전처럼 시간 제한을 두고 문제를 풀어보세요.',
    allOption: '전체',
    examMeta: '{minutes}분 · 문제 {count}개 · 평균 난이도 {difficulty}',
    examAttemptCount: '도전 {n}회',
    examLockedPro: '🔒 Pro 전용',
    startExam: '시작하기',
    sheetCategoryAll: '전체',
    sheetCategoryContest: '대회 문제',
    sheetCategoryCompany: '기업 기출',
    sheetCategoryLearning: '단계별 학습',
    sheetCategoryCustom: '나의 세트',
    sheetProblemCount: '문제 {n}개',
    sheetAttemptCount: '도전 {n}회',
    publicProfileLoadFailed: '공개 프로필을 불러오지 못했습니다.',
    publicProfileFollowFailed: '팔로우 처리에 실패했습니다.',
    publicProfileLoading: '공개 프로필을 불러오는 중입니다.',
    publicProfileNotFound: '프로필 정보를 찾을 수 없습니다.',
    publicProfileNoBio: '소개가 아직 없습니다.',
    processing: '처리 중...',
    publicProfileGoMine: '내 프로필로 이동',
    publicProfileStreakDays: '{n}일',
    publicProfileDistributionTitle: '풀이 분포',
    publicProfileDistributionDesc: '티어별 해결 문제 수를 요약합니다.',
    publicProfileSolvedProblems: '해결 문제',
    publicProfileThirtyDayActivityTitle: '30일 활동',
    publicProfileThirtyDayActivityDesc: '최근 풀이 흐름을 잔디로 확인합니다.',
    publicProfileRecentThirtyDays: '최근 30일 풀이 활동 잔디',
    publicProfileRewardsTitle: '배지 쇼케이스',
    publicProfileRewardsDesc: '획득한 배지와 칭호를 최대 9개까지 표시합니다.',
    publicProfileNoRewards: '표시할 보상이 없습니다.',
    publicProfileMoreRewards: '+{n}개 더',
    publicProfileSubmissionsPrivate: '이 사용자는 제출을 비공개로 설정했습니다.',
    publicProfileRecentSubmissions: '최근 공개 제출 12건',
    publicProfileSubmissionListHidden: '제출 비공개 설정으로 인해 목록을 표시하지 않습니다.',
    publicProfileNoSubmissions: '표시할 공개 제출이 없습니다.',
    publicProfileProblemFallback: '문제 {id}',
    publicProfileCommunityTitle: '커뮤니티 활동',
    publicProfileCommunityDesc: '최근 공개 게시글과 반응 수',
    publicProfileNoPosts: '표시할 게시글이 없습니다.',
    publicProfileSummaryTitle: '프로필 요약',
    publicProfileJoinedDate: '가입일',
    publicProfileSolvedCount: '해결 문제',
    publicProfileTotalLikes: '받은 좋아요',
    publicProfileReplyCount: '댓글 수',
    publicProfileAcceptedAnswers: '채택 답변',
    publicProfileActivityTitle: '활동 피드',
    publicProfileActivityDesc: '풀이, 게시글, 배틀 결과를 시간순으로 표시합니다.',
    publicProfileNoActivity: '최근 활동이 없습니다.',
    publicProfileActivitySolve: '풀이 완료',
    publicProfileActivityPost: '커뮤니티 글 작성',
    rankingLoginRequired: '로그인이 필요합니다.',
    rankingUnfollowed: '언팔로우했습니다.',
    rankingFollowed: '팔로우했습니다! 🎉',
    rankingGenericError: '오류가 발생했습니다.',
    rankingSeasonSummary: '{season} · {count}명',
    rankingThisSeason: '이번 시즌',
    rankingGlobalSummary: '전체 {count}명이 참여하고 있어요',
    rankingGlobalMode: '전체',
    rankingSeasonMode: '이번 시즌',
    rankingSeasonEndsIn: '시즌 종료까지 {n}일',
    rankingMyCurrentRank: '내 현재 순위',
    rankingMe: '나',
    rankingRankLabel: '순위',
    rankingStreakDays: '{n}일',
    rankingHighestTier: '최고 티어',
    rankingLoadFailedTitle: '랭킹을 새로 불러오지 못했습니다.',
    rankingShowingCached: '기존 캐시 데이터를 표시하고 있습니다.',
    rankingRetryLater: '잠시 후 다시 시도해주세요.',
    rankingSearchPlaceholder: '닉네임 검색...',
    rankingAllTiers: '전체 티어',
    rankingSortByRating: '레이팅 순',
    rankingSortBySolved: '풀이 수 순',
    rankingGoToMine: '내 랭킹으로 이동',
    rankingLoading: '랭킹 로딩 중...',
    rankingTopPlayers: 'Top 3 플레이어',
    rankingPoints: '{n}점',
    rankingPlayerLabel: '플레이어',
    rankingNoDataTitle: '랭킹 데이터를 불러오지 못했어요',
    rankingNoDataErrorDesc: '네트워크 상태를 확인한 뒤 다시 시도해 보세요.',
    rankingNoDataSearchDesc: '다른 닉네임이나 티어 필터를 시도해 보세요.',
    rankingSeasonWinsScore: '{wins}승 · 시즌 점수 {score}',
    rankingJoinedOn: '가입 {date}',
    rankingFollowing: '팔로잉',
    rankingPageSummary: '페이지 {page} / {totalPages} · 총 {total}명',
    aiQuickQuestion1: '오늘 어떤 문제를 풀면 좋을까요?',
    aiQuickQuestion2: 'DP 문제 푸는 팁을 알려주세요',
    aiQuickQuestion3: '다음 티어로 올라가려면 어떻게 해야 하나요?',
    aiQuickQuestion4: '알고리즘 공부 순서를 알려주세요',
    aiLocalLevel: '{username}님은 {tier} 수준으로 꾸준히 성장하고 있습니다.',
    aiStrength1: '기본 입출력 처리',
    aiStrength2: '수학 문제 능숙',
    aiWeakness1: '동적 프로그래밍 보완 필요',
    aiWeakness2: '그래프 탐색 학습 필요',
    aiRecommend1: '계단 오르기',
    aiRecommend2: '피보나치 수',
    aiMotivation: '🔥 꾸준히 하면 반드시 실력이 늘어요!',
    aiNextMilestone: '레이팅 {rating}점 달성',
    aiHintFallback1: '문제를 다시 읽어보세요.',
    aiHintFallback2: '예제를 손으로 시뮬레이션해보세요.',
    aiHintFallback3: '관련 알고리즘을 찾아보세요.',
    aiHintFallbackMistake: '엣지 케이스 확인',
    aiHintFallbackConcept: '알고리즘',
    menu: '메뉴',
    aiHintsLabel: 'AI 힌트',
    toggleTheme: '테마 전환',
    ratingPoints: '{n}점',
    korean: '한국어',
    learningPathLoading: '학습 경로를 불러오는 중...',
    learningPathStart: '시작하기 →',
    examLoading: '시험을 불러오는 중...',
    examSummary: '{minutes}분 · 문제 {count}개',
    examResultTitle: '결과',
    examScoreSummary: '점수 {score} / {total}',
    examProblemResult: '문제 {id} · {result}',
    backToExamList: '목록으로',
    examProblemTitle: '문제 {n}',
    examTierLabel: '티어 {tier}',
    examSimulatorDesc: '실전 환경 시뮬레이션입니다. 현재는 각 문제를 기존 채점 엔진으로 제출합니다.',
    editorLoading: '에디터 로딩 중...',
    submitAll: '전체 제출',
    emailVerifyFeatureAi: '🤖 AI 멘토링 · 힌트 · 코드 리뷰',
    emailVerifyFeatureContest: '🏆 대회 참가',
    emailVerifyFeatureBattle: '⚔️ 1:1 배틀 매칭',
    emailVerifyFeatureRanking: '📊 랭킹 등록',
    publicProfilePublicSubmissionsTitle: '공개 제출',
    sheetDetailLoading: '문제 세트를 불러오는 중...',
    yearSuffix: '년',
    pwVeryWeak: '매우 약함',
    pwWeak: '약함',
    pwMedium: '보통',
    pwStrong: '강함',
    pwVeryStrong: '매우 강함',
    authFeatureJudgeTitle: '실시간 채점',
    authFeatureJudgeDesc: 'Docker 샌드박스로 코드를 즉시 채점합니다',
    authFeatureAiTitle: 'AI 멘토링',
    authFeatureAiDesc: 'Gemini AI가 힌트·리뷰·문제 추천을 제공합니다',
    authFeatureContestTitle: '대회 시스템',
    authFeatureContestDesc: '실시간 순위와 함께 다른 개발자와 경쟁하세요',
    authFeatureGrowthTitle: '성장 분석',
    authFeatureGrowthDesc: '잔디·레이팅·뱃지로 실력 향상을 추적합니다',
    authLoggedIn: '로그인됐습니다.',
    authRegistered: '가입이 완료됐습니다.',
    authPlatformSubtitle: '알고리즘 학습 플랫폼',
    authUsersJoined: '명 가입',
    authProblemsCount: '개 문제',
    authCorrectCount: '회 정답',
    authModeLoginDesc: 'DailyCoding 계정으로 시작하세요.',
    authModeRegisterDesc: '지금 가입하고 코딩을 시작하세요.',
    authContinueWithEmail: '또는 이메일로 계속하기',
    authNicknamePlaceholder: '사용할 닉네임 (2자 이상)',
    authPasswordPlaceholderRegister: '8자 이상 입력',
    authPasswordPlaceholderLogin: '비밀번호 입력',
    authAgreePrefix: '계속 진행하면',
    authTermsLabel: '서비스 이용약관',
    authAgreeAnd: '및',
    authPrivacyLabel: '개인정보 처리방침',
    authAgreeSuffix: '에 동의하게 됩니다.',
    submissionsCorrect: '정답',
    submissionsWrong: '틀렸습니다',
    submissionsWrongShort: '틀림',
    submissionsTimeout: '시간 초과',
    submissionsTimeoutShort: '시간초과',
    submissionsErrorShort: '에러',
    submissionsCompileShort: '컴파일',
    submissionsJudging: '채점 중',
    submissionsLoadFailed: '제출 기록을 불러오지 못했습니다.',
    submissionsCompareMineOnly: '내 제출만 비교할 수 있습니다.',
    submissionsCompareSameProblem: '같은 문제의 제출끼리만 비교할 수 있습니다.',
    submissionsSubtitle: '전체 제출 보기와 내 제출만 보기, 문제 번호/유저 검색을 지원합니다.',
    submissionsShowing: '표시 중',
    submissionsAccuracy: '정답률',
    submissionsScope: '범위',
    submissionsScopeAll: '전체 보기',
    submissionsScopeMine: '내꺼만',
    submissionsSearchPlaceholder: '문제 번호, 유저 ID, 닉네임, 문제명 검색',
    submissionsResult: '결과',
    submissionsAllLang: '전체 언어',
    submissionsCompareCount: '비교 선택 {n}/2',
    submissionsViewDiff: 'Diff 보기',
    submissionsClearSelection: '선택 해제',
    submissionsLoadFailedTitle: '제출 기록을 불러오지 못했습니다',
    submissionsEmpty: '제출 기록이 없습니다',
    submissionsProblemFallback: '문제 #{id}',
    submissionsUserLabel: '유저 #{id}',
    submissionsSelected: '선택됨',
    submissionsCompareSelect: '비교 선택',
    submissionsMyCode: '내 제출 코드',
    submissionsCodeLoading: '코드 로딩 중...',
    submissionsNoCode: '// 코드 없음',
    submissionsCodeLoadFailed: '// 코드를 불러올 수 없습니다.',
    submissionsNoOtherCode: '다른 사용자의 코드는 볼 수 없습니다.',
    submissionsDiffTitle: '제출 Diff 비교',
    submissionsDiffLeft: '좌측: #{id} · {date}',
    submissionsDiffRight: '우측: #{id} · {date}',
    submissionsDiffLoading: 'Diff editor 로딩 중...',
    pricingMonthlySuffix: '/월',
    pricingAnnualSuffix: '/년',
    pricingWon: '원',
    pricingMostPopular: '✨ 가장 인기있는 플랜',
    pricingSaveSeventeen: '월간 결제 대비 약 17% 절약',
    pricingTwoMonthsFree: '2개월 무료',
    pricingFaqTitle: '자주 묻는 질문',
    pricingFaqSubtitle: '구독 전에 많이 묻는 항목만 정리했습니다.',
    dashboardAdminTitle: '관리자 대시보드',
    dashboardAdminDesc: '플랫폼 현황을 확인하고 관리하세요.',
    dashboardRegisteredProblems: '등록 문제',
    dashboardActiveUsers: '활성 유저',
    dashboardRecentRanking: '최근 랭킹',
    dashboardCreateProblem: '문제 만들기',
    dashboardManageContest: '대회 관리',
    dashboardGenerateAiProblem: 'AI 문제 생성',
    dashboardGreetingLine: '오늘도 꾸준히 성장하고 있어요. 지금 흐름이면 다음 티어까지 안정적으로 전진할 수 있습니다.',
    dashboardStreakValue: '🔥 {n}일',
    dashboardAccuracy: '정복률',
    dashboardProblemsDelta: '+5 이번 주',
    dashboardGrowthDelta: '+{n} 성장',
    dashboardMyRank: '내 랭킹',
    dashboardRealtimeTrack: '실시간 추적',
    dashboardPromotionActive: '승급전 진행 중',
    dashboardPromotionRecord: '{from} → {to} | {wins}승 {losses}패 (3승 2패제)',
    dashboardPromotionAchieved: '{tier} 달성!',
    dashboardPromotionDesc: '승급전 {wins}승으로 {from}에서 {to}로 승급했습니다.',
    dashboardCheckRanking: '랭킹 확인하기',
    dashboardDailyMissions: '오늘의 미션',
    dashboardReferralTitle: '친구 초대하고 Pro 받기',
    dashboardReferralDescPrefix: '친구가 가입 후 첫 문제를 풀면',
    dashboardReferralReward: 'Pro 7일',
    dashboardReferralDescSuffix: '이 추가됩니다',
    dashboardReferralStats: '초대 {referrals}명 | 보상 {rewards}회 받음',
    dashboardWeeklyProblem: '이번 주의 문제',
    dashboardRewardLabel: '보상',
    dashboardCompleted: '완료',
    dashboardStreakCalendar: '스트릭 캘린더 (52주)',
    dashboardActivityDays: '{n}일 활동',
    dashboardSolvedProblemsCount: '{n}문제',
    dashboardNoRecord: '기록 없음',
    dashboardLowActivity: '적음',
    dashboardHighActivity: '많음',
    dashboardEstimatedTime: '⏱ 예상 {n}분',
    dashboardSolvedYesterday: '✅ 어제 {n}명이 풀었어요',
    dashboardSolveNow: '풀기 →',
    dashboardTierConquest: '티어별 문제 정복',
    dashboardViewAll: '전체 보기 →',
    dashboardRankingLoading: '랭킹 데이터 로딩 중...',
    dashboardRecentSubmissionFeed: '최근 제출 피드',
    dashboardGoSolve: '문제 풀러 가기 →',
    dashboardFollowActivity: '팔로우 활동',
    dashboardUserSuffix: '님이',
    dashboardSolvedWithLang: '{lang}으로 풀었습니다',
    dashboardWrotePost: '글을 작성했습니다',
    dashboardNoProblems: '문제가 없습니다',
    dashboardRandomDefense: '랜덤 디펜스',
    dashboardRoadmap: '알고리즘 로드맵',
    dashboardRoadmapStep1: '입출력 & 수학',
    dashboardRoadmapStep2: '조건문 & 반복문',
    dashboardRoadmapStep3: '배열 & 정렬',
    dashboardRoadmapStep4: '스택 & 큐',
    dashboardRoadmapStep5: '완전 탐색',
    dashboardRoadmapStep6: '그래프 탐색',
    dashboardRoadmapStep7: '동적 프로그래밍',
    dashboardRoadmapStep8: '고급 알고리즘',
    dashboardProblemsUnit: '문제',
    contestJoinSuccess: '✅ "{name}" 참가 완료!',
    contestJoinPending: '⏳ "{name}" 참가 신청 완료 (승인 대기)',
    contestJoinPendingDesc: '⏳ 참가 신청 완료! 관리자 승인을 기다려주세요.',
    contestJoinFailed: '참가 실패',
    contestCreateSuccess: '🏆 대회 "{name}" 생성됐습니다!',
    contestCreateFailed: '생성 실패',
    contestApproved: '승인되었습니다.',
    contestRejected: '거절되었습니다.',
    contestProcessFailed: '처리 실패',
    contestDeleted: '🗑 대회 삭제됨',
    contestDeleteFailed: '삭제 실패',
    contestProblemAdded: '✅ 문제 추가됨',
    contestProblemAddFailed: '추가 실패',
    contestProblemRemoved: '문제 제거됨',
    contestProblemRemoveFailed: '제거 실패',
    contestCustomProblemAdded: '✅ 대회 전용 문제가 추가됐습니다.',
    contestCustomProblemFailed: '대회 문제 생성 실패',
    contestFeatureLabel: '대회 기능',
    contestSearchPlaceholder: '대회 이름 또는 설명 검색...',
    contestSearchEmpty: '"{query}"에 대한 검색 결과가 없습니다.',
    contestMineEmpty: '아직 참가 중인 대회가 없습니다.',
    contestEndedEmpty: '종료된 대회가 없습니다.',
    contestUpcomingEmpty: '예정된 대회가 없습니다.',
    contestLiveEmpty: '진행 중인 대회가 없습니다.',
    contestClearSearch: '검색어 초기화',
    contestDurationMinutes: '{n}분',
    contestParticipants: '{current}/{max}명',
    contestHost: '주최: {host}',
    contestApprovalRequired: '승인 필요',
  },
  en: {
    // ── Navigation ─────────────────────────────
    problems: 'Problems',
    contest: 'Contest',
    ranking: 'Ranking',
    community: 'Community',
    battle: 'Battle',
    settings: 'Settings',
    logout: 'Logout',
    profile: 'Profile',
    myProfile: 'My Profile',
    mypage: 'My Page',
    exams: 'Mock Exam',
    sheets: 'Problem Sets',
    learning: 'Learning Path',
    subscribe: 'Subscription',
    pricing: 'Pricing',
    ai: 'AI Analysis',
    submissions: 'Submissions',
    admin: 'Admin',
    team: 'Team',
    // ── Theme / Language ────────────────────────
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    systemMode: 'System',
    language: 'Language',
    // ── Notifications ───────────────────────────
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications',
    // ── Common UI ───────────────────────────────
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    prev: 'Prev',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    loading: 'Loading…',
    loadingMore: 'Loading more…',
    noData: 'No data',
    noResults: 'No results found',
    tryAgain: 'Try again',
    showMore: 'Show more',
    showLess: 'Show less',
    copied: 'Copied',
    copyFailed: 'Failed to copy link',
    share: 'Share',
    submit: 'Submit',
    run: 'Run',
    upgrade: 'Upgrade',
    // ── Stats ───────────────────────────────────
    tier: 'Tier',
    solved: 'Solved',
    rating: 'Rating',
    streak: 'Streak',
    today: 'Today',
    week: 'This Week',
    solvedCount: 'Problems',
    submissionCount: 'Submissions',
    // ── Profile ─────────────────────────────────
    editProfile: 'Edit Profile',
    saveProfile: 'Save Profile',
    bio: 'Bio',
    nickname: 'Nickname',
    displayName: 'Display Name',
    socialLinks: 'Social Links',
    techStack: 'Tech Stack',
    followers: 'Followers',
    following: 'Following',
    follow: 'Follow',
    unfollow: 'Unfollow',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    // ── Auth ────────────────────────────────────
    login: 'Login',
    register: 'Sign Up',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    loginWithGoogle: 'Continue with Google',
    loginWithGithub: 'Continue with GitHub',
    // ── Problems ────────────────────────────────
    problemList: 'Problems',
    difficulty: 'Difficulty',
    tags: 'Tags',
    unsolved: 'Unsolved',
    bookmarked: 'Bookmarked',
    addBookmark: 'Added to bookmarks',
    removeBookmark: 'Remove bookmark',
    premium: 'Premium',
    premiumOnly: 'Premium only',
    randomProblem: 'Random Unsolved',
    findingRandom: 'Finding random…',
    noSolvedProblems: 'No solved problems yet',
    sortByMostSolved: 'Most solved',
    sortByLatest: 'Latest',
    // ── Judge ────────────────────────────────────
    runCode: 'Run Code',
    submitCode: 'Submit',
    testCases: 'Test Cases',
    output: 'Output',
    accepted: 'Accepted!',
    wrongAnswer: 'Wrong Answer',
    timeLimitExceeded: 'Time Limit Exceeded',
    memoryLimitExceeded: 'Memory Limit Exceeded',
    runtimeError: 'Runtime Error',
    compileError: 'Compile Error',
    hint: 'Hint',
    aiHint: 'AI Hint',
    discuss: 'Discuss',
    editorial: 'Editorial',
    myCode: 'My Code',
    reset: 'Reset',
    fontSize: 'Font Size',
    // ── Community ────────────────────────────────
    post: 'Post',
    comment: 'Comment',
    like: 'Like',
    noComments: 'No comments yet',
    writeComment: 'Write a comment',
    write: 'Write',
    popularPosts: 'Popular',
    recentPosts: 'Recent',
    report: 'Report',
    // ── Dashboard ────────────────────────────────
    welcome: 'Hello',
    recommendedProblems: "Today's Picks",
    tryProblem: 'Try It',
    quickAction: 'Quick Actions',
    activityHeatmap: 'Activity',
    growthChart: 'Growth',
    weeklyChallenge: 'Weekly Challenge',
    // ── Battle ────────────────────────────────────
    findOpponent: 'Find Opponent',
    battleHistory: 'Battle History',
    spectate: 'Spectate',
    win: 'Win',
    lose: 'Loss',
    draw: 'Draw',
    waiting: 'Waiting…',
    // ── Contest ───────────────────────────────────
    ongoing: 'Ongoing',
    upcoming: 'Upcoming',
    ended: 'Ended',
    joinContest: 'Register',
    // ── AI Page ───────────────────────────────────
    analyze: 'Analyze',
    aiReview: 'AI Code Review',
    dailyQuiz: "Today's Quiz",
    aiChat: 'AI Chat',
    // ── Settings tabs ────────────────────────────
    profileTab: 'Profile',
    notificationsTab: 'Notifications',
    uiTab: 'Display',
    editorTab: 'Editor',
    privacyTab: 'Privacy',
    accountTab: 'Account',
    // ── Settings — UI ────────────────────────────
    animations: 'Animations',
    animationsDesc: 'Page transition effects',
    compactMode: 'Compact Mode',
    compactModeDesc: 'Denser problem list',
    autoCollapseSidebar: 'Auto-collapse Sidebar',
    appFont: 'App Font',
    appFontDesc: 'Saved font applies across the whole app.',
    // ── Settings — editor ─────────────────────────
    autoSave: 'Auto Save',
    autoSaveDesc: 'Save code every 30s',
    minimap: 'Minimap',
    minimapDesc: 'Show editor minimap',
    lineNumbers: 'Line Numbers',
    tabSize: 'Tab Size',
    editorTheme: 'Editor Theme',
    // ── Settings — notifications ──────────────────
    commentNotif: 'Comment Notifications',
    commentNotifDesc: 'When someone comments on your post',
    likeNotif: 'Like Notifications',
    likeNotifDesc: 'When your post or comment gets liked',
    followNotif: 'Follow Notifications',
    followNotifDesc: 'When you get a new follower',
    mentionNotif: 'Mention Notifications',
    mentionNotifDesc: 'When you are mentioned in a comment',
    battleNotif: 'Battle Notifications',
    battleNotifDesc: 'Battle invites and results',
    // ── Settings — privacy ────────────────────────
    profileVisibility: 'Profile Visibility',
    postVisibility: 'Post Visibility',
    visPublic: 'Public',
    visFollowers: 'Followers Only',
    visPrivate: 'Private',
    // ── Toast / status messages ───────────────────
    saveSuccess: 'Saved!',
    saveFailed: 'Save failed',
    loadFailed: 'Failed to load',
    profileSaved: 'Profile saved!',
    passwordChanged: 'Password changed!',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Must be at least 8 characters',
    settingsLoadFailed: 'Failed to load settings.',
    visibilitySaved: 'Visibility settings saved!',
    // ── ErrorBoundary ──────────────────────────────
    unexpectedError: 'An unexpected error occurred',
    refreshFix: 'Refreshing the page may fix this.',
    errorDetails: 'Error Details',
    refresh: '🔄 Refresh',
    goBack: '← Go Back',
    // ── EmailVerifyGate ────────────────────────────
    emailVerifyRequired: 'Email Verification Required',
    afterVerification: 'Available After Verification',
    resendEmailBtn: '📧 Resend Verification Email',
    sending: 'Sending...',
    emailResent: '✓ Verification email sent. Check your inbox.',
    noVerifyForProblems: 'Solving problems is available without verification.',
    // ── NotFoundPage ───────────────────────────────
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'The requested page does not exist or has moved.',
    pageNotFoundHint: 'Check the URL or use the links below.',
    goHome: '🏠 Home',
    // ── Auth pages ─────────────────────────────────
    resetPassword: 'Reset Password',
    resetPasswordDesc: 'Enter your email address to receive a reset link.',
    sendResetLink: 'Send Reset Link',
    sendingLink: 'Sending...',
    checkEmail: 'Check Your Email',
    checkEmailDesc: 'We sent a password reset link to your email. Check your inbox or spam folder.',
    backToLogin: 'Back to Login',
    setNewPassword: 'Set New Password',
    newPasswordDesc: 'Enter your new password below.',
    invalidLink: '⚠️ Invalid link. Please request a new password reset.',
    passwordChangedTitle: 'Password Changed',
    passwordChangedRedirect: 'Your password has been updated. Redirecting to login in 3 seconds.',
    goToLogin: 'Go to Login',
    passwordMinLength: 'Password must be at least 8 characters.',
    passwordMismatch2: 'Passwords do not match.',
    resetFailed: 'Password reset failed. The link may have expired.',
    changingPassword: 'Changing...',
    changePasswordBtn: 'Change Password',
    min8Chars: 'Min. 8 characters',
    reEnterPassword: 'Re-enter password',
    passwordsMatch: '✓ Passwords match',
    passwordsNoMatch: '✗ Passwords do not match',
    // ── VerifyEmailPage ────────────────────────────
    verifyingEmail: 'Verifying email...',
    pleaseWait: 'Please wait.',
    verifySuccess: 'Verification Complete!',
    verifySuccessDesc: 'Email verified successfully. Redirecting to dashboard in 3 seconds.',
    goToDashboard: 'Go to Dashboard',
    verifyFailed: 'Verification Failed',
    invalidLinkSimple: 'Invalid link.',
    verifyFailedDefault: 'Email verification failed. The link may have expired.',
    resendSuccess: '✓ Verification email sent. Check your inbox.',
    resendRequest: 'Resend',
    // ── SharedSubmissionPage ───────────────────────
    loadingShare: 'Loading shared link...',
    sharedSubmission: 'Shared Submission',
    cannotOpenLink: 'Cannot Open Link',
    goHomeLink: 'Go Home',
    codeLoading: 'Loading code...',
    authorLabel: 'Author',
    resultLabel: 'Result',
    langLabel: 'Language',
    solveTimeLabel: 'Solve Time',
    codeLabel: 'Code',
    // ── ProblemsPage ───────────────────────────────
    allTiers: 'All Tiers',
    allTypes: 'All Types',
    loadingTags: 'Loading tags...',
    allTags: 'All Tags',
    sortById: 'By Number',
    sortByEasy: 'Easiest First',
    sortByHard: 'Hardest First',
    allStatus: 'All',
    solvedStatus: 'Solved',
    unsolvedStatus: 'Unsolved',
    bookmarkStatus: 'Bookmarked',
    viewingAll: 'Viewing all problems',
    copyFilterLink: 'Copy Filter Link',
    clearAll: 'Reset',
    solve: 'Solve →',
    solveProblem: '💻 Start Solving →',
    loadingProblems: 'Loading problems...',
    noResultsHint: 'Try different filters or pick a random problem.',
    manageProblem: 'Manage Problems',
    upgradeAndSolve: '🔒 Upgrade to Pro to Solve',
    prevPage: '← Prev',
    nextPage: 'Next →',
    onboardingRec: '🎯 Recommended for You',
    sortByNewest: 'Newest',
    sortBySolved: 'Most Solved',
    randomPicking: 'Searching...',
    randomPick: 'Pick Random',
    localFallback: 'Local Fallback',
    filterLoadingDesc: 'Preparing results for your filters...',
    hoverSolve: 'Hover to solve',
    problemNoDesc: 'See problem description in detail view.',
    searchPlaceholder: 'Search problems...',
    chipSearch: 'Search: ',
    chipTier: 'Tier: ',
    chipType: 'Type: ',
    chipTag: 'Tag: ',
    chipStatus: 'Status: ',
    chipSort: 'Sort: ',
    totalLabel: 'Total',
    solvedLabel: '✓ Solved',
    unsolvedLabel: '◯ Unsolved',
    currentResults: 'Results',
    pageInfo: 'Page {page} / {total}',
    showingOf: 'Showing {showing} of {total}',
    activeFilters: '{n} active filter(s)',
    difficultyShort: 'Difficulty',
    solversCount: '{n} solvers',
    solversUnit: '{n}',
    tableNumCol: '#',
    tableTitleCol: 'Title',
    tableTierCol: 'Tier',
    tableDiffCol: 'Diff.',
    tableSolversCol: 'Solvers',
    tableRateCol: 'Rate',
    tableStatusCol: 'Status',
    tableActionCol: 'Action',
    exInput: 'Input',
    exOutput: 'Output',
    problemListTitle: '📋 Problems',
    filterLinkCopied: 'Filter link copied.',
    filterLinkFailed: 'Failed to copy. Check browser permissions.',
    bookmarkAdded: '🔖 Bookmarked.',
    bookmarkRemoved: 'Bookmark removed.',
    bookmarkFailed: 'Failed to update bookmark.',
    filterCleared: 'Filters cleared.',
    upgradeRequired: 'Premium problem. Upgrade required.',
    randomNone: 'No matching problems found.',
    randomFailed: 'Failed to pick random problem.',
    randomPicked: '🎲 Selected: {title}',
    loadFailed2: 'Failed to load. Showing local data.',
    solvedBadge: '✅ Solved',
    premiumBadge: '🔒 Premium',
    typeLabelCoding: 'General',
    typeShortCoding: 'Code',
    typeLabelFillBlank: 'Fill Blank',
    typeShortFillBlank: 'Blank',
    typeLabelBugFix: 'Bug Fix',
    typeShortBugFix: 'Bug',
    secUnit: 's',
    // ── AiPage ────────────────────────────────────
    analyzingBtn: '✨ Analyze My Skills',
    analyzingStatus: 'Analyzing...',
    generatingQuiz: 'Generating...',
    aiOnline: '• Online',
    sendMessage: 'Send',
    hintReceive: 'Get Hint',
    hintAnalyzing: 'Analyzing',
    hintNoSelect: '-- Select Problem --',
    hintExceeded: 'All hints used for today.',
    hintLimitTitle: 'Daily Hint Limit Reached',
    noRecommendation: 'No recommendations yet. Solve more problems!',
    aiFeatureLabel: 'AI Features',
    aiPageTitle: '🤖 AI Personalized Picks',
    aiPageSubtitle: 'Gemini AI analyzes your history to suggest the best learning path.',
    quotaUnlimited: 'Remaining today: Unlimited (Pro/Team)',
    quotaRemaining: 'Remaining today: {n}',
    quotaExceeded: 'You have used all AI calls for today.',
    upgradeLink: 'Upgrade to Pro',
    upgradeUnlimitedSuffix: ' for unlimited access.',
    todayQuizBtn: '🎯 Today\'s Quiz',
    recommendCardTitle: '🎯 Recommended Problems',
    recommendCardSubtitle: 'Unsolved problems matched to your tier.',
    loadingText: 'Loading...',
    aiEmptyPrompt: 'Click the button to start AI analysis.',
    aiEmptyPrompt2: 'Gemini AI will give you personalized recommendations.',
    previewProblems: 'problems analyzed',
    previewStreak: 'day streak',
    previewTier: 'tier',
    quizCardTitle: '🎯 Today\'s Quiz',
    quizCorrect: '🎉 Correct!',
    quizWrong: '❌ Wrong!',
    quizRelatedConcept: 'Related: ',
    hintCardTitle: '💡 Problem AI Hint',
    hintCardSubtitle: 'Select a problem to receive step-by-step hints.',
    hintUpgradeLink: 'Upgrade to Pro',
    hintUpgradeSuffix: ' for unlimited hints.',
    hintRemainingCount: '{n} hints remaining today (Free plan)',
    hintProPlanLink: 'View Pro Plan →',
    hintLevelBtn: 'Hint {n}',
    hintCommonMistake: '⚠️ Common mistake: ',
    hintRelatedConcept: 'Related concept: ',
    aiAnalyzingText: 'Gemini AI is analyzing...',
    analysisCurrentLevel: '📊 Current Level',
    analysisStrengths: '💪 Strengths',
    analysisWeaknesses: '📈 Areas to Improve',
    analysisRecommended: '🎯 Recommended Problems',
    analysisStudyPlan: '📅 This Week\'s Study Plan',
    defaultStudyPlan: 'Try solving one problem every day!',
    chatWelcomeLine1: 'Hello, {username}!',
    chatWelcomeLine2: 'Ask me anything about your algorithm studies.',
    chatPlaceholder: 'Ask about your studies... (Enter to send)',
    chatRetryMsg: 'Please try again in a moment.',
    // ── BattlePage ─────────────────────────────────
    codingBattle: 'Coding Battle',
    inviteOpponent: 'Invite Opponent',
    sendInviteBtn: 'Send Invite',
    acceptBtn: 'Accept',
    declineBtn: 'Decline',
    activeBattlesTab: 'Active Battles',
    historyTabLabel: 'History',
    activeBattlesSpectate: 'Active Battles (Spectatable)',
    noBattles: 'No active battles.',
    spectateBtn: 'Spectate',
    myBattleHistory: 'My Battle History',
    loadingHistory: 'Loading history...',
    noBattleHistory: 'No completed battles yet.',
    rematchBtn: 'Rematch',
    battleRules: 'Battle Rules',
    spectatorBanner: '👁️ Spectating (read-only)',
    freePlanBanner: 'Free plan users can battle with ads displayed.',
    judgingCode: 'Judging...',
    wrongAnswerFeedback: 'Wrong answer. Try again.',
    correctFeedback: 'Correct! Territory claimed 🎉',
    battleWin: '🏆 Victory!',
    battleDraw: '🤝 Draw',
    battleLose: '💀 Defeat',
    noRatingEffect: 'ℹ️ Battle results do not affect rating or tier.',
    battleAgain: 'Battle Again',
    battleSubtitle: 'Challenge opponents in real-time coding battles.',
    battleTagline: 'Claim all territories (problems) first to win!',
    inviteInputPlaceholder: 'Enter opponent username',
    waitingAcceptance: 'Waiting for {name} to accept...',
    waitingSub: 'Opponent must accept within 2 minutes.',
    inviteReceived: '{name} has challenged you to a battle!',
    inviteExpiry: 'Auto-expires in 2 minutes if not accepted.',
    scoreHistory: 'Score {scoreFor} : {scoreAgainst} · Solved {solvedFor} : {solvedAgainst}',
    rematchRequesting: 'Requesting...',
    historyBtn: '🕘 History',
    copyBtn: '📋 Copy',
    twitterBtn: '🐦 Twitter',
    opponentTypingLabel: '⌨️ Typing...',
    myTerritoryFlag: '🏳️ Mine',
    lockedTerritoryFlag: '🔒 Locked',
    lockedByOpponentBadge: '🔒 Claimed by opponent',
    myTeamFlag: '🏳️ My Team',
    oppTeamFlag: '🏴 Opp. Team',
    teamCaptured: '{team} claimed this territory.',
    submitBtn: 'Submit',
    resultSelf: '(me)',
    resultPts: '{n} pts',
    resultSolved: '{n} solved',
    territoryResult: 'Territory Results',
    battleRuleTime: '⏱️ Time limit: <strong>30 minutes</strong>',
    battleRuleTerritory: '🗺️ Territory: The first team to solve a problem claims it; the opponent cannot attempt it.',
    battleRuleTeam: '👥 Team Battle: Team scores are combined. Communicate and divide problems!',
    battleRuleSpectate: '👁️ Spectate Mode: Watch other players\' battles in real time.',
    inviteFailedDefault: 'Failed to send invite',
    declinedInvite: 'Opponent declined the invite.',
    spectateFailed: 'Failed to spectate.',
    shareShared: 'Result shared.',
    shareCopied: 'Result copied to clipboard.',
    shareFailed: 'Failed to share result.',
    rematchSent: 'Rematch request sent.',
    rematchFailed: 'Failed to send rematch request.',
    hintPrefix: '💡 Hint: ',
    blankPlaceholder: 'Blank {n}',
    bugfixLabel: 'Enter corrected line:',
    bugfixPlaceholder: 'Enter the corrected line without the bug',
    exampleLabel: 'Example {n}',
    langUnspecified: 'No language',
    resultCorrect: '✅ Correct',
    resultLocked: '🔒 Locked',
    resultWrong: '❌ Wrong',
    codePlaceholder: 'Enter your code...',
    // ── ContestPage ────────────────────────────────
    contestMode: '🏆 Contest Mode',
    contestAdminDesc: 'Create and manage contests.',
    contestUserDesc: 'Join contests to compete.',
    createContestBtn: '+ Create Contest',
    allContests: 'All',
    liveContests: 'Live',
    endedContests: 'Ended',
    myContests: 'My Contests',
    noContestsCurrent: 'No contests at the moment.',
    createFirstContest: 'No contests yet. Create one!',
    seeResults: 'See Results',
    joinContestBtn: 'Join',
    enterNow: '🔴 Enter Now',
    joinDone: '✓ Joined',
    approvalPending: '⏳ Pending Approval',
    // ── Additional i18n batch ─────────────────────
    sendFailedTryLater: 'Failed to send. Please try again shortly.',
    verifyBannerMessage: 'Email verification is required. Please check your inbox.',
    mockAdRemoveTitle: '🚀 Remove ads with Pro',
    mockAdRemoveDesc: 'Focus on coding in a cleaner environment.',
    mockAdAiTitle: '💡 Need more AI hints?',
    mockAdAiDesc: 'The Pro plan gives you unlimited AI mentoring.',
    mockAdRankingTitle: '🏆 Aim for rank #1',
    mockAdRankingDesc: 'Earn higher ratings with premium problems.',
    mockAdBenefitsCta: 'See benefits',
    goalJobHunting: 'Pass Coding Tests',
    goalJobHuntingDesc: 'Preparing for a job change or interviews',
    goalSkillUp: 'Improve Skills',
    goalSkillUpDesc: 'Level up your algorithm skills',
    goalInterviewPrep: 'Interview Prep',
    goalInterviewPrepDesc: 'Get ready for technical interviews',
    goalFun: 'Just for Fun',
    goalFunDesc: 'Stay consistent and enjoy the process',
    onboardingBeginner: 'Beginner',
    onboardingBeginnerDesc: 'I know basics like bubble sort and core syntax',
    onboardingIntermediate: 'Intermediate',
    onboardingIntermediateDesc: 'I can solve arrays, strings, and some BFS/DFS',
    onboardingAdvanced: 'Advanced',
    onboardingAdvancedDesc: 'I am consistently preparing for real coding tests',
    onboardingGoalTitle: 'Why did you come to DailyCoding?',
    onboardingGoalDesc: 'We will prepare the first problems and learning flow that fit you.',
    onboardingLevelTitle: 'What is your current level?',
    onboardingLevelDesc: 'We will avoid giving you problems that are too hard or too easy.',
    onboardingCompanyTitle: 'Which company are you preparing for?',
    onboardingCompanyDesc: 'Optional. If you add one, recommendations become more tailored.',
    onboardingCompanyPlaceholder: 'Kakao, Naver, Line, Toss ...',
    skip: 'Skip',
    getStarted: 'Get Started',
    teamCreated: 'Team created.',
    teamCreateFailed: 'Failed to create team',
    teamInviteCopied: 'Invite link copied to clipboard. (Valid for 7 days)',
    teamInviteFailed: 'Failed to create invite link',
    teamRemoveConfirm: 'Are you sure you want to remove this member from the team?',
    teamMemberRemoved: 'Member removed.',
    teamMemberRemoveFailed: 'Failed to remove member',
    teamPlanOnlyTitle: 'This page is for the Team plan only.',
    teamPlanOnlyDesc: 'Upgrade your plan to use the team dashboard.',
    viewPricing: 'View Pricing',
    teamCreateTitle: 'Create your team',
    teamCreateDesc: 'Your team membership is active. Name your team and create the first one.',
    teamNamePlaceholder: 'Enter a team name (e.g. Dev Team, Algo Study)',
    teamCreateBtn: 'Create Team',
    teamManageDesc: 'Manage your team members and track learning progress.',
    teamInviteBtn: 'Invite Member',
    teamStatsBeta: 'Team Stats (Beta)',
    teamActiveMembers: 'Active Members',
    teamWeeklySolved: 'Solved This Week',
    teamWeeklySolvedCount: '{n}',
    teamAvgRating: 'Average Rating',
    teamRatingPoints: '{n} pts',
    teamMemberList: 'Members',
    teamUserCol: 'User',
    teamRoleCol: 'Role',
    teamJoinedAtCol: 'Joined',
    teamStatusCol: 'Status',
    teamActionCol: 'Action',
    teamYou: 'You',
    teamActiveStatus: '● Active',
    teamRemoveBtn: 'Remove',
    examListDesc: 'Practice with time limits just like a real coding test.',
    allOption: 'All',
    examMeta: '{minutes} min · {count} problems · avg difficulty {difficulty}',
    examAttemptCount: '{n} attempts',
    examLockedPro: '🔒 Pro only',
    startExam: 'Start',
    sheetCategoryAll: 'All',
    sheetCategoryContest: 'Contest Problems',
    sheetCategoryCompany: 'Company Past Sets',
    sheetCategoryLearning: 'Learning Path',
    sheetCategoryCustom: 'My Sets',
    sheetProblemCount: '{n} problems',
    sheetAttemptCount: '{n} attempts',
    publicProfileLoadFailed: 'Failed to load public profile.',
    publicProfileFollowFailed: 'Failed to update follow state.',
    publicProfileLoading: 'Loading public profile...',
    publicProfileNotFound: 'Profile not found.',
    publicProfileNoBio: 'No bio yet.',
    processing: 'Processing...',
    publicProfileGoMine: 'Go to My Profile',
    publicProfileStreakDays: '{n} days',
    publicProfileDistributionTitle: 'Solved Distribution',
    publicProfileDistributionDesc: 'Summary of solved problems by tier.',
    publicProfileSolvedProblems: 'Solved',
    publicProfileThirtyDayActivityTitle: '30-Day Activity',
    publicProfileThirtyDayActivityDesc: 'Check recent solving flow with a heatmap.',
    publicProfileRecentThirtyDays: 'Heatmap of recent 30 days',
    publicProfileRewardsTitle: 'Badge Showcase',
    publicProfileRewardsDesc: 'Display up to 9 earned badges and titles.',
    publicProfileNoRewards: 'No rewards to display.',
    publicProfileMoreRewards: '+{n} more',
    publicProfileSubmissionsPrivate: 'This user has set submissions to private.',
    publicProfileRecentSubmissions: 'Recent 12 public submissions',
    publicProfileSubmissionListHidden: 'Submission list is hidden due to privacy settings.',
    publicProfileNoSubmissions: 'No public submissions to display.',
    publicProfileProblemFallback: 'Problem {id}',
    publicProfileCommunityTitle: 'Community Activity',
    publicProfileCommunityDesc: 'Recent public posts and reactions',
    publicProfileNoPosts: 'No posts to display.',
    publicProfileSummaryTitle: 'Profile Summary',
    publicProfileJoinedDate: 'Joined',
    publicProfileSolvedCount: 'Solved Problems',
    publicProfileTotalLikes: 'Likes Received',
    publicProfileReplyCount: 'Replies',
    publicProfileAcceptedAnswers: 'Accepted Answers',
    publicProfileActivityTitle: 'Activity Feed',
    publicProfileActivityDesc: 'Shows solves, posts, and battle results in time order.',
    publicProfileNoActivity: 'No recent activity.',
    publicProfileActivitySolve: 'Solved',
    publicProfileActivityPost: 'Community Post',
    rankingLoginRequired: 'Login is required.',
    rankingUnfollowed: 'Unfollowed.',
    rankingFollowed: 'Followed! 🎉',
    rankingGenericError: 'An error occurred.',
    rankingSeasonSummary: '{season} · {count} players',
    rankingThisSeason: 'This Season',
    rankingGlobalSummary: '{count} players are participating overall',
    rankingGlobalMode: 'Global',
    rankingSeasonMode: 'This Season',
    rankingSeasonEndsIn: '{n} days until season end',
    rankingMyCurrentRank: 'My Current Rank',
    rankingMe: 'Me',
    rankingRankLabel: 'Rank',
    rankingStreakDays: '{n} days',
    rankingHighestTier: 'Highest Tier',
    rankingLoadFailedTitle: 'Failed to refresh ranking data.',
    rankingShowingCached: 'Showing cached ranking data.',
    rankingRetryLater: 'Please try again later.',
    rankingSearchPlaceholder: 'Search nickname...',
    rankingAllTiers: 'All Tiers',
    rankingSortByRating: 'By Rating',
    rankingSortBySolved: 'By Solved',
    rankingGoToMine: 'Go to My Rank',
    rankingLoading: 'Loading rankings...',
    rankingTopPlayers: 'Top 3 Players',
    rankingPoints: '{n} pts',
    rankingPlayerLabel: 'Player',
    rankingNoDataTitle: 'Unable to load ranking data',
    rankingNoDataErrorDesc: 'Check your network connection and try again.',
    rankingNoDataSearchDesc: 'Try a different nickname or tier filter.',
    rankingSeasonWinsScore: '{wins} wins · season score {score}',
    rankingJoinedOn: 'Joined {date}',
    rankingFollowing: 'Following',
    rankingPageSummary: 'Page {page} / {totalPages} · total {total}',
    aiQuickQuestion1: 'What problem should I solve today?',
    aiQuickQuestion2: 'Can you give me tips for DP problems?',
    aiQuickQuestion3: 'How can I reach the next tier?',
    aiQuickQuestion4: 'What order should I study algorithms in?',
    aiLocalLevel: '{username} is steadily improving at the {tier} level.',
    aiStrength1: 'Handles basic input/output well',
    aiStrength2: 'Comfortable with math problems',
    aiWeakness1: 'Needs more dynamic programming practice',
    aiWeakness2: 'Should study graph traversal more',
    aiRecommend1: 'Climbing Stairs',
    aiRecommend2: 'Fibonacci Number',
    aiMotivation: '🔥 Keep going and your skills will definitely improve!',
    aiNextMilestone: 'Reach rating {rating}',
    aiHintFallback1: 'Read the problem again carefully.',
    aiHintFallback2: 'Try simulating the sample by hand.',
    aiHintFallback3: 'Look up the related algorithm.',
    aiHintFallbackMistake: 'Check edge cases',
    aiHintFallbackConcept: 'Algorithm',
    menu: 'Menu',
    aiHintsLabel: 'AI Hints',
    toggleTheme: 'Toggle Theme',
    ratingPoints: '{n} pts',
    korean: 'Korean',
    learningPathLoading: 'Loading learning path...',
    learningPathStart: 'Start →',
    examLoading: 'Loading exam...',
    examSummary: '{minutes} min · {count} problems',
    examResultTitle: 'Result',
    examScoreSummary: 'Score {score} / {total}',
    examProblemResult: 'Problem {id} · {result}',
    backToExamList: 'Back to list',
    examProblemTitle: 'Problem {n}',
    examTierLabel: 'Tier {tier}',
    examSimulatorDesc: 'This simulates a real exam environment. Each problem is currently submitted through the existing judge engine.',
    editorLoading: 'Loading editor...',
    submitAll: 'Submit All',
    emailVerifyFeatureAi: '🤖 AI mentoring · hints · code review',
    emailVerifyFeatureContest: '🏆 Join contests',
    emailVerifyFeatureBattle: '⚔️ 1:1 battle matching',
    emailVerifyFeatureRanking: '📊 Ranking registration',
    publicProfilePublicSubmissionsTitle: 'Public Submissions',
    sheetDetailLoading: 'Loading problem set...',
    yearSuffix: '',
    pwVeryWeak: 'Very Weak',
    pwWeak: 'Weak',
    pwMedium: 'Medium',
    pwStrong: 'Strong',
    pwVeryStrong: 'Very Strong',
    authFeatureJudgeTitle: 'Real-time Judging',
    authFeatureJudgeDesc: 'Judge code instantly with a Docker sandbox',
    authFeatureAiTitle: 'AI Mentoring',
    authFeatureAiDesc: 'Gemini AI provides hints, reviews, and problem recommendations',
    authFeatureContestTitle: 'Contest System',
    authFeatureContestDesc: 'Compete with other developers in live rankings',
    authFeatureGrowthTitle: 'Growth Analytics',
    authFeatureGrowthDesc: 'Track progress with heatmaps, ratings, and badges',
    authLoggedIn: 'Logged in.',
    authRegistered: 'Registration complete.',
    authPlatformSubtitle: 'Algorithm learning platform',
    authUsersJoined: 'users joined',
    authProblemsCount: 'problems',
    authCorrectCount: 'correct answers',
    authModeLoginDesc: 'Start with your DailyCoding account.',
    authModeRegisterDesc: 'Sign up now and start coding.',
    authContinueWithEmail: 'or continue with email',
    authNicknamePlaceholder: 'Choose a nickname (at least 2 characters)',
    authPasswordPlaceholderRegister: 'Enter at least 8 characters',
    authPasswordPlaceholderLogin: 'Enter your password',
    authAgreePrefix: 'By continuing, you agree to the',
    authTermsLabel: 'Terms of Service',
    authAgreeAnd: 'and',
    authPrivacyLabel: 'Privacy Policy',
    authAgreeSuffix: '.',
    submissionsCorrect: 'Correct',
    submissionsWrong: 'Wrong Answer',
    submissionsWrongShort: 'Wrong',
    submissionsTimeout: 'Time Limit Exceeded',
    submissionsTimeoutShort: 'Timeout',
    submissionsErrorShort: 'Error',
    submissionsCompileShort: 'Compile',
    submissionsJudging: 'Judging',
    submissionsLoadFailed: 'Failed to load submissions.',
    submissionsCompareMineOnly: 'Only your own submissions can be compared.',
    submissionsCompareSameProblem: 'Only submissions from the same problem can be compared.',
    submissionsSubtitle: 'Supports viewing all submissions or only yours, plus search by problem/user.',
    submissionsShowing: 'Showing',
    submissionsAccuracy: 'Accuracy',
    submissionsScope: 'Scope',
    submissionsScopeAll: 'Show All',
    submissionsScopeMine: 'Mine Only',
    submissionsSearchPlaceholder: 'Search by problem ID, user ID, nickname, or title',
    submissionsResult: 'Result',
    submissionsAllLang: 'All Languages',
    submissionsCompareCount: 'Compare {n}/2',
    submissionsViewDiff: 'View Diff',
    submissionsClearSelection: 'Clear',
    submissionsLoadFailedTitle: 'Failed to load submissions',
    submissionsEmpty: 'No submissions found',
    submissionsProblemFallback: 'Problem #{id}',
    submissionsUserLabel: 'User #{id}',
    submissionsSelected: 'Selected',
    submissionsCompareSelect: 'Compare',
    submissionsMyCode: 'My Submission Code',
    submissionsCodeLoading: 'Loading code...',
    submissionsNoCode: '// No code',
    submissionsCodeLoadFailed: '// Failed to load code.',
    submissionsNoOtherCode: 'You cannot view other users\' code.',
    submissionsDiffTitle: 'Submission Diff',
    submissionsDiffLeft: 'Left: #{id} · {date}',
    submissionsDiffRight: 'Right: #{id} · {date}',
    submissionsDiffLoading: 'Loading diff editor...',
    pricingMonthlySuffix: '/mo',
    pricingAnnualSuffix: '/yr',
    pricingWon: ' KRW',
    pricingMostPopular: '✨ Most Popular Plan',
    pricingSaveSeventeen: 'Save about 17% vs monthly billing',
    pricingTwoMonthsFree: '2 months free',
    pricingFaqTitle: 'Frequently Asked Questions',
    pricingFaqSubtitle: 'A short list of common questions before subscribing.',
    dashboardAdminTitle: 'Admin Dashboard',
    dashboardAdminDesc: 'Check platform status and manage operations.',
    dashboardRegisteredProblems: 'Problems Added',
    dashboardActiveUsers: 'Active Users',
    dashboardRecentRanking: 'Recent Ranking',
    dashboardCreateProblem: 'Create Problem',
    dashboardManageContest: 'Manage Contest',
    dashboardGenerateAiProblem: 'Generate AI Problem',
    dashboardGreetingLine: 'You are growing steadily today as well. At this pace, you are on track for the next tier.',
    dashboardStreakValue: '🔥 {n} days',
    dashboardAccuracy: 'Coverage',
    dashboardProblemsDelta: '+5 this week',
    dashboardGrowthDelta: '+{n} growth',
    dashboardMyRank: 'My Rank',
    dashboardRealtimeTrack: 'Real-time tracking',
    dashboardPromotionActive: 'Promotion Match Active',
    dashboardPromotionRecord: '{from} → {to} | {wins}W {losses}L (best of 5)',
    dashboardPromotionAchieved: 'Reached {tier}!',
    dashboardPromotionDesc: 'Promoted from {from} to {to} with {wins} wins in promotion matches.',
    dashboardCheckRanking: 'Check Ranking',
    dashboardDailyMissions: 'Today\'s Missions',
    dashboardReferralTitle: 'Invite Friends, Get Pro',
    dashboardReferralDescPrefix: 'If a friend signs up and solves their first problem, you get',
    dashboardReferralReward: '7 days of Pro',
    dashboardReferralDescSuffix: 'added.',
    dashboardReferralStats: '{referrals} invites | {rewards} rewards claimed',
    dashboardWeeklyProblem: 'Problem of the Week',
    dashboardRewardLabel: 'Reward',
    dashboardCompleted: 'Completed',
    dashboardStreakCalendar: 'Streak Calendar (52 weeks)',
    dashboardActivityDays: '{n} active days',
    dashboardSolvedProblemsCount: '{n} solved',
    dashboardNoRecord: 'No record',
    dashboardLowActivity: 'Less',
    dashboardHighActivity: 'More',
    dashboardEstimatedTime: '⏱ Est. {n} min',
    dashboardSolvedYesterday: '✅ Solved by {n} users yesterday',
    dashboardSolveNow: 'Solve →',
    dashboardTierConquest: 'Tier Conquest',
    dashboardViewAll: 'View All →',
    dashboardRankingLoading: 'Loading ranking data...',
    dashboardRecentSubmissionFeed: 'Recent Submission Feed',
    dashboardGoSolve: 'Go Solve Problems →',
    dashboardFollowActivity: 'Follow Activity',
    dashboardUserSuffix: '',
    dashboardSolvedWithLang: 'solved it in {lang}',
    dashboardWrotePost: 'wrote a post',
    dashboardNoProblems: 'No problems available',
    dashboardRandomDefense: 'Random Defense',
    dashboardRoadmap: 'Algorithm Roadmap',
    dashboardRoadmapStep1: 'I/O & Math',
    dashboardRoadmapStep2: 'Conditions & Loops',
    dashboardRoadmapStep3: 'Arrays & Sorting',
    dashboardRoadmapStep4: 'Stack & Queue',
    dashboardRoadmapStep5: 'Brute Force',
    dashboardRoadmapStep6: 'Graph Traversal',
    dashboardRoadmapStep7: 'Dynamic Programming',
    dashboardRoadmapStep8: 'Advanced Algorithms',
    dashboardProblemsUnit: ' problems',
    contestJoinSuccess: '✅ Joined "{name}"!',
    contestJoinPending: '⏳ Requested to join "{name}" (awaiting approval)',
    contestJoinPendingDesc: '⏳ Join request submitted. Please wait for approval.',
    contestJoinFailed: 'Failed to join contest',
    contestCreateSuccess: '🏆 Contest "{name}" created!',
    contestCreateFailed: 'Failed to create contest',
    contestApproved: 'Approved.',
    contestRejected: 'Rejected.',
    contestProcessFailed: 'Failed to process request',
    contestDeleted: '🗑 Contest deleted',
    contestDeleteFailed: 'Failed to delete contest',
    contestProblemAdded: '✅ Problem added',
    contestProblemAddFailed: 'Failed to add problem',
    contestProblemRemoved: 'Problem removed',
    contestProblemRemoveFailed: 'Failed to remove problem',
    contestCustomProblemAdded: '✅ Contest-only problem added.',
    contestCustomProblemFailed: 'Failed to create contest problem',
    contestFeatureLabel: 'Contest features',
    contestSearchPlaceholder: 'Search contest name or description...',
    contestSearchEmpty: 'No results found for "{query}".',
    contestMineEmpty: 'You have not joined any contests yet.',
    contestEndedEmpty: 'No ended contests.',
    contestUpcomingEmpty: 'No upcoming contests.',
    contestLiveEmpty: 'No live contests.',
    contestClearSearch: 'Clear search',
    contestDurationMinutes: '{n} min',
    contestParticipants: '{current}/{max} users',
    contestHost: 'Host: {host}',
    contestApprovalRequired: 'Approval required',
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('dc_lang') || 'ko');

  const value = useMemo(() => ({
    lang,
    t: (key) => STRINGS[lang]?.[key] || STRINGS.ko[key] || key,
    setLang: (next) => {
      setLang(next);
      localStorage.setItem('dc_lang', next);
    },
    toggleLang: () => {
      const next = lang === 'ko' ? 'en' : 'ko';
      setLang(next);
      localStorage.setItem('dc_lang', next);
    },
  }), [lang]);

  return (
    <LangContext.Provider value={value}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LangContext);
  if (!context) throw new Error('useLang must be used within a LangProvider');
  return context;
}

// Exported for class components that cannot use hooks (e.g. ErrorBoundary)
export const STRINGS_EB = {
  ko: {
    unexpectedError: STRINGS.ko.unexpectedError,
    refreshFix: STRINGS.ko.refreshFix,
    errorDetails: STRINGS.ko.errorDetails,
    refresh: STRINGS.ko.refresh,
    goBack: STRINGS.ko.goBack,
  },
  en: {
    unexpectedError: STRINGS.en.unexpectedError,
    refreshFix: STRINGS.en.refreshFix,
    errorDetails: STRINGS.en.errorDetails,
    refresh: STRINGS.en.refresh,
    goBack: STRINGS.en.goBack,
  },
};
